// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2025.SCL.2007C5.full
// Entry schema: SCL.xsd

// Package v2007c5 contains generated raw XML types for IEC 61850 SCL
// schema version v2007c5.
//
// Namespace: http://www.iec.ch/61850/2003/SCL
package v2007c5
