// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2025.SCL.2007C5.full
// Entry schema: SCL.xsd
package v2007c5

// AssociationInitiator is generated from xs:simpleType "tAssociationInitiator".
type AssociationInitiator string

const (
	AssociationInitiator_client AssociationInitiator = "client"
	AssociationInitiator_server AssociationInitiator = "server"
)

// AssociationKindEnum is generated from xs:simpleType "tAssociationKindEnum".
type AssociationKindEnum string

const (
	AssociationKindEnum_pre_established AssociationKindEnum = "pre-established"
	AssociationKindEnum_predefined      AssociationKindEnum = "predefined"
)

// AuthenticationEnum is generated from xs:simpleType "tAuthenticationEnum".
type AuthenticationEnum string

const (
	AuthenticationEnum_none        AuthenticationEnum = "none"
	AuthenticationEnum_password    AuthenticationEnum = "password"
	AuthenticationEnum_weak        AuthenticationEnum = "weak"
	AuthenticationEnum_strong      AuthenticationEnum = "strong"
	AuthenticationEnum_certificate AuthenticationEnum = "certificate"
)

// DomainLNGroupAEnum is generated from xs:simpleType "tDomainLNGroupAEnum".
type DomainLNGroupAEnum string

const (
	DomainLNGroupAEnum_ANCR DomainLNGroupAEnum = "ANCR"
	DomainLNGroupAEnum_ARCO DomainLNGroupAEnum = "ARCO"
	DomainLNGroupAEnum_ARIS DomainLNGroupAEnum = "ARIS"
	DomainLNGroupAEnum_ATCC DomainLNGroupAEnum = "ATCC"
	DomainLNGroupAEnum_AVCO DomainLNGroupAEnum = "AVCO"
)

// DomainLNGroupCEnum is generated from xs:simpleType "tDomainLNGroupCEnum".
type DomainLNGroupCEnum string

const (
	DomainLNGroupCEnum_CALH DomainLNGroupCEnum = "CALH"
	DomainLNGroupCEnum_CCGR DomainLNGroupCEnum = "CCGR"
	DomainLNGroupCEnum_CILO DomainLNGroupCEnum = "CILO"
	DomainLNGroupCEnum_CPOW DomainLNGroupCEnum = "CPOW"
	DomainLNGroupCEnum_CSWI DomainLNGroupCEnum = "CSWI"
	DomainLNGroupCEnum_CSYN DomainLNGroupCEnum = "CSYN"
)

// DomainLNGroupFEnum is generated from xs:simpleType "tDomainLNGroupFEnum".
type DomainLNGroupFEnum string

const (
	DomainLNGroupFEnum_FCNT DomainLNGroupFEnum = "FCNT"
	DomainLNGroupFEnum_FCSD DomainLNGroupFEnum = "FCSD"
	DomainLNGroupFEnum_FFIL DomainLNGroupFEnum = "FFIL"
	DomainLNGroupFEnum_FLIM DomainLNGroupFEnum = "FLIM"
	DomainLNGroupFEnum_FPID DomainLNGroupFEnum = "FPID"
	DomainLNGroupFEnum_FRMP DomainLNGroupFEnum = "FRMP"
	DomainLNGroupFEnum_FSPT DomainLNGroupFEnum = "FSPT"
	DomainLNGroupFEnum_FXOT DomainLNGroupFEnum = "FXOT"
	DomainLNGroupFEnum_FXUT DomainLNGroupFEnum = "FXUT"
)

// DomainLNGroupGEnum is generated from xs:simpleType "tDomainLNGroupGEnum".
type DomainLNGroupGEnum string

const (
	DomainLNGroupGEnum_GAPC DomainLNGroupGEnum = "GAPC"
	DomainLNGroupGEnum_GGIO DomainLNGroupGEnum = "GGIO"
	DomainLNGroupGEnum_GLOG DomainLNGroupGEnum = "GLOG"
	DomainLNGroupGEnum_GSAL DomainLNGroupGEnum = "GSAL"
)

// DomainLNGroupIEnum is generated from xs:simpleType "tDomainLNGroupIEnum".
type DomainLNGroupIEnum string

const (
	DomainLNGroupIEnum_IARC DomainLNGroupIEnum = "IARC"
	DomainLNGroupIEnum_IHMI DomainLNGroupIEnum = "IHMI"
	DomainLNGroupIEnum_ISAF DomainLNGroupIEnum = "ISAF"
	DomainLNGroupIEnum_ITCI DomainLNGroupIEnum = "ITCI"
	DomainLNGroupIEnum_ITMI DomainLNGroupIEnum = "ITMI"
	DomainLNGroupIEnum_ITPC DomainLNGroupIEnum = "ITPC"
)

// DomainLNGroupKEnum is generated from xs:simpleType "tDomainLNGroupKEnum".
type DomainLNGroupKEnum string

const (
	DomainLNGroupKEnum_KFAN DomainLNGroupKEnum = "KFAN"
	DomainLNGroupKEnum_KFIL DomainLNGroupKEnum = "KFIL"
	DomainLNGroupKEnum_KPMP DomainLNGroupKEnum = "KPMP"
	DomainLNGroupKEnum_KTNK DomainLNGroupKEnum = "KTNK"
	DomainLNGroupKEnum_KVLV DomainLNGroupKEnum = "KVLV"
)

// DomainLNGroupMEnum is generated from xs:simpleType "tDomainLNGroupMEnum".
type DomainLNGroupMEnum string

const (
	DomainLNGroupMEnum_MDIF DomainLNGroupMEnum = "MDIF"
	DomainLNGroupMEnum_MENV DomainLNGroupMEnum = "MENV"
	DomainLNGroupMEnum_MFLK DomainLNGroupMEnum = "MFLK"
	DomainLNGroupMEnum_MHAI DomainLNGroupMEnum = "MHAI"
	DomainLNGroupMEnum_MHAN DomainLNGroupMEnum = "MHAN"
	DomainLNGroupMEnum_MHYD DomainLNGroupMEnum = "MHYD"
	DomainLNGroupMEnum_MMDC DomainLNGroupMEnum = "MMDC"
	DomainLNGroupMEnum_MMET DomainLNGroupMEnum = "MMET"
	DomainLNGroupMEnum_MMTN DomainLNGroupMEnum = "MMTN"
	DomainLNGroupMEnum_MMTR DomainLNGroupMEnum = "MMTR"
	DomainLNGroupMEnum_MMXN DomainLNGroupMEnum = "MMXN"
	DomainLNGroupMEnum_MMXU DomainLNGroupMEnum = "MMXU"
	DomainLNGroupMEnum_MSQI DomainLNGroupMEnum = "MSQI"
	DomainLNGroupMEnum_MSTA DomainLNGroupMEnum = "MSTA"
)

// DomainLNGroupPEnum is generated from xs:simpleType "tDomainLNGroupPEnum".
type DomainLNGroupPEnum string

const (
	DomainLNGroupPEnum_PDIF DomainLNGroupPEnum = "PDIF"
	DomainLNGroupPEnum_PDIR DomainLNGroupPEnum = "PDIR"
	DomainLNGroupPEnum_PDIS DomainLNGroupPEnum = "PDIS"
	DomainLNGroupPEnum_PDOP DomainLNGroupPEnum = "PDOP"
	DomainLNGroupPEnum_PDUP DomainLNGroupPEnum = "PDUP"
	DomainLNGroupPEnum_PFRC DomainLNGroupPEnum = "PFRC"
	DomainLNGroupPEnum_PHAR DomainLNGroupPEnum = "PHAR"
	DomainLNGroupPEnum_PHIZ DomainLNGroupPEnum = "PHIZ"
	DomainLNGroupPEnum_PIOC DomainLNGroupPEnum = "PIOC"
	DomainLNGroupPEnum_PMRI DomainLNGroupPEnum = "PMRI"
	DomainLNGroupPEnum_PMSS DomainLNGroupPEnum = "PMSS"
	DomainLNGroupPEnum_POPF DomainLNGroupPEnum = "POPF"
	DomainLNGroupPEnum_PPAM DomainLNGroupPEnum = "PPAM"
	DomainLNGroupPEnum_PRTR DomainLNGroupPEnum = "PRTR"
	DomainLNGroupPEnum_PSCH DomainLNGroupPEnum = "PSCH"
	DomainLNGroupPEnum_PSDE DomainLNGroupPEnum = "PSDE"
	DomainLNGroupPEnum_PTEF DomainLNGroupPEnum = "PTEF"
	DomainLNGroupPEnum_PTHF DomainLNGroupPEnum = "PTHF"
	DomainLNGroupPEnum_PTOC DomainLNGroupPEnum = "PTOC"
	DomainLNGroupPEnum_PTOF DomainLNGroupPEnum = "PTOF"
	DomainLNGroupPEnum_PTOV DomainLNGroupPEnum = "PTOV"
	DomainLNGroupPEnum_PTRC DomainLNGroupPEnum = "PTRC"
	DomainLNGroupPEnum_PTTR DomainLNGroupPEnum = "PTTR"
	DomainLNGroupPEnum_PTUC DomainLNGroupPEnum = "PTUC"
	DomainLNGroupPEnum_PTUF DomainLNGroupPEnum = "PTUF"
	DomainLNGroupPEnum_PTUV DomainLNGroupPEnum = "PTUV"
	DomainLNGroupPEnum_PUPF DomainLNGroupPEnum = "PUPF"
	DomainLNGroupPEnum_PVOC DomainLNGroupPEnum = "PVOC"
	DomainLNGroupPEnum_PVPH DomainLNGroupPEnum = "PVPH"
	DomainLNGroupPEnum_PZSU DomainLNGroupPEnum = "PZSU"
)

// DomainLNGroupQEnum is generated from xs:simpleType "tDomainLNGroupQEnum".
type DomainLNGroupQEnum string

const (
	DomainLNGroupQEnum_QFVR DomainLNGroupQEnum = "QFVR"
	DomainLNGroupQEnum_QITR DomainLNGroupQEnum = "QITR"
	DomainLNGroupQEnum_QIUB DomainLNGroupQEnum = "QIUB"
	DomainLNGroupQEnum_QVTR DomainLNGroupQEnum = "QVTR"
	DomainLNGroupQEnum_QVUB DomainLNGroupQEnum = "QVUB"
	DomainLNGroupQEnum_QVVR DomainLNGroupQEnum = "QVVR"
)

// DomainLNGroupREnum is generated from xs:simpleType "tDomainLNGroupREnum".
type DomainLNGroupREnum string

const (
	DomainLNGroupREnum_RADR DomainLNGroupREnum = "RADR"
	DomainLNGroupREnum_RBDR DomainLNGroupREnum = "RBDR"
	DomainLNGroupREnum_RBRF DomainLNGroupREnum = "RBRF"
	DomainLNGroupREnum_RDIR DomainLNGroupREnum = "RDIR"
	DomainLNGroupREnum_RDRE DomainLNGroupREnum = "RDRE"
	DomainLNGroupREnum_RDRS DomainLNGroupREnum = "RDRS"
	DomainLNGroupREnum_RFLO DomainLNGroupREnum = "RFLO"
	DomainLNGroupREnum_RMXU DomainLNGroupREnum = "RMXU"
	DomainLNGroupREnum_RPSB DomainLNGroupREnum = "RPSB"
	DomainLNGroupREnum_RREC DomainLNGroupREnum = "RREC"
	DomainLNGroupREnum_RSYN DomainLNGroupREnum = "RSYN"
)

// DomainLNGroupSEnum is generated from xs:simpleType "tDomainLNGroupSEnum".
type DomainLNGroupSEnum string

const (
	DomainLNGroupSEnum_SARC DomainLNGroupSEnum = "SARC"
	DomainLNGroupSEnum_SCBR DomainLNGroupSEnum = "SCBR"
	DomainLNGroupSEnum_SIMG DomainLNGroupSEnum = "SIMG"
	DomainLNGroupSEnum_SIML DomainLNGroupSEnum = "SIML"
	DomainLNGroupSEnum_SLTC DomainLNGroupSEnum = "SLTC"
	DomainLNGroupSEnum_SOPM DomainLNGroupSEnum = "SOPM"
	DomainLNGroupSEnum_SPDC DomainLNGroupSEnum = "SPDC"
	DomainLNGroupSEnum_SPTR DomainLNGroupSEnum = "SPTR"
	DomainLNGroupSEnum_SSWI DomainLNGroupSEnum = "SSWI"
	DomainLNGroupSEnum_STMP DomainLNGroupSEnum = "STMP"
	DomainLNGroupSEnum_SVBR DomainLNGroupSEnum = "SVBR"
)

// DomainLNGroupTEnum is generated from xs:simpleType "tDomainLNGroupTEnum".
type DomainLNGroupTEnum string

const (
	DomainLNGroupTEnum_TANG DomainLNGroupTEnum = "TANG"
	DomainLNGroupTEnum_TAXD DomainLNGroupTEnum = "TAXD"
	DomainLNGroupTEnum_TCTR DomainLNGroupTEnum = "TCTR"
	DomainLNGroupTEnum_TDST DomainLNGroupTEnum = "TDST"
	DomainLNGroupTEnum_TFLW DomainLNGroupTEnum = "TFLW"
	DomainLNGroupTEnum_TFRQ DomainLNGroupTEnum = "TFRQ"
	DomainLNGroupTEnum_TGSN DomainLNGroupTEnum = "TGSN"
	DomainLNGroupTEnum_THUM DomainLNGroupTEnum = "THUM"
	DomainLNGroupTEnum_TLVL DomainLNGroupTEnum = "TLVL"
	DomainLNGroupTEnum_TMGF DomainLNGroupTEnum = "TMGF"
	DomainLNGroupTEnum_TMVM DomainLNGroupTEnum = "TMVM"
	DomainLNGroupTEnum_TPOS DomainLNGroupTEnum = "TPOS"
	DomainLNGroupTEnum_TPRS DomainLNGroupTEnum = "TPRS"
	DomainLNGroupTEnum_TRTN DomainLNGroupTEnum = "TRTN"
	DomainLNGroupTEnum_TSND DomainLNGroupTEnum = "TSND"
	DomainLNGroupTEnum_TTMP DomainLNGroupTEnum = "TTMP"
	DomainLNGroupTEnum_TTNS DomainLNGroupTEnum = "TTNS"
	DomainLNGroupTEnum_TVBR DomainLNGroupTEnum = "TVBR"
	DomainLNGroupTEnum_TVTR DomainLNGroupTEnum = "TVTR"
	DomainLNGroupTEnum_TWPH DomainLNGroupTEnum = "TWPH"
)

// DomainLNGroupXEnum is generated from xs:simpleType "tDomainLNGroupXEnum".
type DomainLNGroupXEnum string

const (
	DomainLNGroupXEnum_XCBR DomainLNGroupXEnum = "XCBR"
	DomainLNGroupXEnum_XSWI DomainLNGroupXEnum = "XSWI"
)

// DomainLNGroupYEnum is generated from xs:simpleType "tDomainLNGroupYEnum".
type DomainLNGroupYEnum string

const (
	DomainLNGroupYEnum_YEFN DomainLNGroupYEnum = "YEFN"
	DomainLNGroupYEnum_YLTC DomainLNGroupYEnum = "YLTC"
	DomainLNGroupYEnum_YPSH DomainLNGroupYEnum = "YPSH"
	DomainLNGroupYEnum_YPTR DomainLNGroupYEnum = "YPTR"
)

// DomainLNGroupZEnum is generated from xs:simpleType "tDomainLNGroupZEnum".
type DomainLNGroupZEnum string

const (
	DomainLNGroupZEnum_ZAXN DomainLNGroupZEnum = "ZAXN"
	DomainLNGroupZEnum_ZBAT DomainLNGroupZEnum = "ZBAT"
	DomainLNGroupZEnum_ZBSH DomainLNGroupZEnum = "ZBSH"
	DomainLNGroupZEnum_ZCAB DomainLNGroupZEnum = "ZCAB"
	DomainLNGroupZEnum_ZCAP DomainLNGroupZEnum = "ZCAP"
	DomainLNGroupZEnum_ZCON DomainLNGroupZEnum = "ZCON"
	DomainLNGroupZEnum_ZGEN DomainLNGroupZEnum = "ZGEN"
	DomainLNGroupZEnum_ZGIL DomainLNGroupZEnum = "ZGIL"
	DomainLNGroupZEnum_ZLIN DomainLNGroupZEnum = "ZLIN"
	DomainLNGroupZEnum_ZMOT DomainLNGroupZEnum = "ZMOT"
	DomainLNGroupZEnum_ZREA DomainLNGroupZEnum = "ZREA"
	DomainLNGroupZEnum_ZRES DomainLNGroupZEnum = "ZRES"
	DomainLNGroupZEnum_ZRRC DomainLNGroupZEnum = "ZRRC"
	DomainLNGroupZEnum_ZSAR DomainLNGroupZEnum = "ZSAR"
	DomainLNGroupZEnum_ZSCR DomainLNGroupZEnum = "ZSCR"
	DomainLNGroupZEnum_ZSMC DomainLNGroupZEnum = "ZSMC"
	DomainLNGroupZEnum_ZTCF DomainLNGroupZEnum = "ZTCF"
	DomainLNGroupZEnum_ZTCR DomainLNGroupZEnum = "ZTCR"
)

// ExtControlCheck is generated from xs:simpleType "tExtControlCheck".
type ExtControlCheck string

const (
	ExtControlCheck_true     ExtControlCheck = "true"
	ExtControlCheck_false    ExtControlCheck = "false"
	ExtControlCheck_conserve ExtControlCheck = "conserve"
)

// GSEControlTypeEnum is generated from xs:simpleType "tGSEControlTypeEnum".
type GSEControlTypeEnum string

const (
	GSEControlTypeEnum_GSSE  GSEControlTypeEnum = "GSSE"
	GSEControlTypeEnum_GOOSE GSEControlTypeEnum = "GOOSE"
)

// LLN0Enum is generated from xs:simpleType "tLLN0Enum".
type LLN0Enum string

const (
	LLN0Enum_LLN0 LLN0Enum = "LLN0"
)

// LPHDEnum is generated from xs:simpleType "tLPHDEnum".
type LPHDEnum string

const (
	LPHDEnum_LPHD LPHDEnum = "LPHD"
)

// PhaseEnum is generated from xs:simpleType "tPhaseEnum".
type PhaseEnum string

const (
	PhaseEnum_A    PhaseEnum = "A"
	PhaseEnum_B    PhaseEnum = "B"
	PhaseEnum_C    PhaseEnum = "C"
	PhaseEnum_N    PhaseEnum = "N"
	PhaseEnum_all  PhaseEnum = "all"
	PhaseEnum_none PhaseEnum = "none"
	PhaseEnum_AB   PhaseEnum = "AB"
	PhaseEnum_BC   PhaseEnum = "BC"
	PhaseEnum_CA   PhaseEnum = "CA"
)

// PowerTransformerEnum is generated from xs:simpleType "tPowerTransformerEnum".
type PowerTransformerEnum string

const (
	PowerTransformerEnum_PTR PowerTransformerEnum = "PTR"
)

// PredefinedAttributeNameEnum is generated from xs:simpleType "tPredefinedAttributeNameEnum".
type PredefinedAttributeNameEnum string

const (
	PredefinedAttributeNameEnum_T                PredefinedAttributeNameEnum = "T"
	PredefinedAttributeNameEnum_Test             PredefinedAttributeNameEnum = "Test"
	PredefinedAttributeNameEnum_Check            PredefinedAttributeNameEnum = "Check"
	PredefinedAttributeNameEnum_SIUnit           PredefinedAttributeNameEnum = "SIUnit"
	PredefinedAttributeNameEnum_Oper             PredefinedAttributeNameEnum = "Oper"
	PredefinedAttributeNameEnum_SBO              PredefinedAttributeNameEnum = "SBO"
	PredefinedAttributeNameEnum_SBOw             PredefinedAttributeNameEnum = "SBOw"
	PredefinedAttributeNameEnum_Cancel           PredefinedAttributeNameEnum = "Cancel"
	PredefinedAttributeNameEnum_Addr             PredefinedAttributeNameEnum = "Addr"
	PredefinedAttributeNameEnum_PRIORITY         PredefinedAttributeNameEnum = "PRIORITY"
	PredefinedAttributeNameEnum_VID              PredefinedAttributeNameEnum = "VID"
	PredefinedAttributeNameEnum_APPID            PredefinedAttributeNameEnum = "APPID"
	PredefinedAttributeNameEnum_TransportInUse   PredefinedAttributeNameEnum = "TransportInUse"
	PredefinedAttributeNameEnum_IPClassOfTraffic PredefinedAttributeNameEnum = "IPClassOfTraffic"
	PredefinedAttributeNameEnum_IPv6FlowLabel    PredefinedAttributeNameEnum = "IPv6FlowLabel"
	PredefinedAttributeNameEnum_IPAddressLength  PredefinedAttributeNameEnum = "IPAddressLength"
	PredefinedAttributeNameEnum_IPAddress        PredefinedAttributeNameEnum = "IPAddress"
)

// PredefinedBasicTypeEnum is generated from xs:simpleType "tPredefinedBasicTypeEnum".
type PredefinedBasicTypeEnum string

const (
	PredefinedBasicTypeEnum_BOOLEAN      PredefinedBasicTypeEnum = "BOOLEAN"
	PredefinedBasicTypeEnum_INT8         PredefinedBasicTypeEnum = "INT8"
	PredefinedBasicTypeEnum_INT16        PredefinedBasicTypeEnum = "INT16"
	PredefinedBasicTypeEnum_INT24        PredefinedBasicTypeEnum = "INT24"
	PredefinedBasicTypeEnum_INT32        PredefinedBasicTypeEnum = "INT32"
	PredefinedBasicTypeEnum_INT64        PredefinedBasicTypeEnum = "INT64"
	PredefinedBasicTypeEnum_INT128       PredefinedBasicTypeEnum = "INT128"
	PredefinedBasicTypeEnum_INT8U        PredefinedBasicTypeEnum = "INT8U"
	PredefinedBasicTypeEnum_INT16U       PredefinedBasicTypeEnum = "INT16U"
	PredefinedBasicTypeEnum_INT24U       PredefinedBasicTypeEnum = "INT24U"
	PredefinedBasicTypeEnum_INT32U       PredefinedBasicTypeEnum = "INT32U"
	PredefinedBasicTypeEnum_FLOAT32      PredefinedBasicTypeEnum = "FLOAT32"
	PredefinedBasicTypeEnum_FLOAT64      PredefinedBasicTypeEnum = "FLOAT64"
	PredefinedBasicTypeEnum_Enum         PredefinedBasicTypeEnum = "Enum"
	PredefinedBasicTypeEnum_Dbpos        PredefinedBasicTypeEnum = "Dbpos"
	PredefinedBasicTypeEnum_Tcmd         PredefinedBasicTypeEnum = "Tcmd"
	PredefinedBasicTypeEnum_Quality      PredefinedBasicTypeEnum = "Quality"
	PredefinedBasicTypeEnum_Timestamp    PredefinedBasicTypeEnum = "Timestamp"
	PredefinedBasicTypeEnum_VisString32  PredefinedBasicTypeEnum = "VisString32"
	PredefinedBasicTypeEnum_VisString64  PredefinedBasicTypeEnum = "VisString64"
	PredefinedBasicTypeEnum_VisString65  PredefinedBasicTypeEnum = "VisString65"
	PredefinedBasicTypeEnum_VisString129 PredefinedBasicTypeEnum = "VisString129"
	PredefinedBasicTypeEnum_VisString255 PredefinedBasicTypeEnum = "VisString255"
	PredefinedBasicTypeEnum_Octet64      PredefinedBasicTypeEnum = "Octet64"
	PredefinedBasicTypeEnum_Unicode255   PredefinedBasicTypeEnum = "Unicode255"
	PredefinedBasicTypeEnum_Struct       PredefinedBasicTypeEnum = "Struct"
	PredefinedBasicTypeEnum_EntryTime    PredefinedBasicTypeEnum = "EntryTime"
	PredefinedBasicTypeEnum_Check        PredefinedBasicTypeEnum = "Check"
	PredefinedBasicTypeEnum_ObjRef       PredefinedBasicTypeEnum = "ObjRef"
	PredefinedBasicTypeEnum_Currency     PredefinedBasicTypeEnum = "Currency"
	PredefinedBasicTypeEnum_PhyComAddr   PredefinedBasicTypeEnum = "PhyComAddr"
	PredefinedBasicTypeEnum_TrgOps       PredefinedBasicTypeEnum = "TrgOps"
	PredefinedBasicTypeEnum_OptFlds      PredefinedBasicTypeEnum = "OptFlds"
	PredefinedBasicTypeEnum_SvOptFlds    PredefinedBasicTypeEnum = "SvOptFlds"
	PredefinedBasicTypeEnum_LogOptFlds   PredefinedBasicTypeEnum = "LogOptFlds"
	PredefinedBasicTypeEnum_EntryID      PredefinedBasicTypeEnum = "EntryID"
	PredefinedBasicTypeEnum_Octet6       PredefinedBasicTypeEnum = "Octet6"
	PredefinedBasicTypeEnum_Octet16      PredefinedBasicTypeEnum = "Octet16"
)

// PredefinedCDCEnum is generated from xs:simpleType "tPredefinedCDCEnum".
type PredefinedCDCEnum string

const (
	PredefinedCDCEnum_SPS   PredefinedCDCEnum = "SPS"
	PredefinedCDCEnum_DPS   PredefinedCDCEnum = "DPS"
	PredefinedCDCEnum_INS   PredefinedCDCEnum = "INS"
	PredefinedCDCEnum_ENS   PredefinedCDCEnum = "ENS"
	PredefinedCDCEnum_ACT   PredefinedCDCEnum = "ACT"
	PredefinedCDCEnum_ACD   PredefinedCDCEnum = "ACD"
	PredefinedCDCEnum_SEC   PredefinedCDCEnum = "SEC"
	PredefinedCDCEnum_BCR   PredefinedCDCEnum = "BCR"
	PredefinedCDCEnum_HST   PredefinedCDCEnum = "HST"
	PredefinedCDCEnum_VSS   PredefinedCDCEnum = "VSS"
	PredefinedCDCEnum_MV    PredefinedCDCEnum = "MV"
	PredefinedCDCEnum_CMV   PredefinedCDCEnum = "CMV"
	PredefinedCDCEnum_SAV   PredefinedCDCEnum = "SAV"
	PredefinedCDCEnum_WYE   PredefinedCDCEnum = "WYE"
	PredefinedCDCEnum_DEL   PredefinedCDCEnum = "DEL"
	PredefinedCDCEnum_SEQ   PredefinedCDCEnum = "SEQ"
	PredefinedCDCEnum_HMV   PredefinedCDCEnum = "HMV"
	PredefinedCDCEnum_HWYE  PredefinedCDCEnum = "HWYE"
	PredefinedCDCEnum_HDEL  PredefinedCDCEnum = "HDEL"
	PredefinedCDCEnum_SPC   PredefinedCDCEnum = "SPC"
	PredefinedCDCEnum_DPC   PredefinedCDCEnum = "DPC"
	PredefinedCDCEnum_INC   PredefinedCDCEnum = "INC"
	PredefinedCDCEnum_ENC   PredefinedCDCEnum = "ENC"
	PredefinedCDCEnum_BSC   PredefinedCDCEnum = "BSC"
	PredefinedCDCEnum_ISC   PredefinedCDCEnum = "ISC"
	PredefinedCDCEnum_APC   PredefinedCDCEnum = "APC"
	PredefinedCDCEnum_BAC   PredefinedCDCEnum = "BAC"
	PredefinedCDCEnum_SPG   PredefinedCDCEnum = "SPG"
	PredefinedCDCEnum_ING   PredefinedCDCEnum = "ING"
	PredefinedCDCEnum_ENG   PredefinedCDCEnum = "ENG"
	PredefinedCDCEnum_ORG   PredefinedCDCEnum = "ORG"
	PredefinedCDCEnum_TSG   PredefinedCDCEnum = "TSG"
	PredefinedCDCEnum_CUG   PredefinedCDCEnum = "CUG"
	PredefinedCDCEnum_VSG   PredefinedCDCEnum = "VSG"
	PredefinedCDCEnum_ASG   PredefinedCDCEnum = "ASG"
	PredefinedCDCEnum_CURVE PredefinedCDCEnum = "CURVE"
	PredefinedCDCEnum_CSG   PredefinedCDCEnum = "CSG"
	PredefinedCDCEnum_DPL   PredefinedCDCEnum = "DPL"
	PredefinedCDCEnum_LPL   PredefinedCDCEnum = "LPL"
	PredefinedCDCEnum_CSD   PredefinedCDCEnum = "CSD"
	PredefinedCDCEnum_CST   PredefinedCDCEnum = "CST"
	PredefinedCDCEnum_BTS   PredefinedCDCEnum = "BTS"
	PredefinedCDCEnum_UTS   PredefinedCDCEnum = "UTS"
	PredefinedCDCEnum_LTS   PredefinedCDCEnum = "LTS"
	PredefinedCDCEnum_GTS   PredefinedCDCEnum = "GTS"
	PredefinedCDCEnum_MTS   PredefinedCDCEnum = "MTS"
	PredefinedCDCEnum_NTS   PredefinedCDCEnum = "NTS"
	PredefinedCDCEnum_STS   PredefinedCDCEnum = "STS"
	PredefinedCDCEnum_CTS   PredefinedCDCEnum = "CTS"
	PredefinedCDCEnum_OTS   PredefinedCDCEnum = "OTS"
	PredefinedCDCEnum_VSD   PredefinedCDCEnum = "VSD"
	PredefinedCDCEnum_ORS   PredefinedCDCEnum = "ORS"
	PredefinedCDCEnum_TCS   PredefinedCDCEnum = "TCS"
)

// PredefinedCommonConductingEquipmentEnum is generated from xs:simpleType "tPredefinedCommonConductingEquipmentEnum".
type PredefinedCommonConductingEquipmentEnum string

const (
	PredefinedCommonConductingEquipmentEnum_CBR PredefinedCommonConductingEquipmentEnum = "CBR"
	PredefinedCommonConductingEquipmentEnum_DIS PredefinedCommonConductingEquipmentEnum = "DIS"
	PredefinedCommonConductingEquipmentEnum_VTR PredefinedCommonConductingEquipmentEnum = "VTR"
	PredefinedCommonConductingEquipmentEnum_CTR PredefinedCommonConductingEquipmentEnum = "CTR"
	PredefinedCommonConductingEquipmentEnum_GEN PredefinedCommonConductingEquipmentEnum = "GEN"
	PredefinedCommonConductingEquipmentEnum_CAP PredefinedCommonConductingEquipmentEnum = "CAP"
	PredefinedCommonConductingEquipmentEnum_REA PredefinedCommonConductingEquipmentEnum = "REA"
	PredefinedCommonConductingEquipmentEnum_CON PredefinedCommonConductingEquipmentEnum = "CON"
	PredefinedCommonConductingEquipmentEnum_MOT PredefinedCommonConductingEquipmentEnum = "MOT"
	PredefinedCommonConductingEquipmentEnum_EFN PredefinedCommonConductingEquipmentEnum = "EFN"
	PredefinedCommonConductingEquipmentEnum_PSH PredefinedCommonConductingEquipmentEnum = "PSH"
	PredefinedCommonConductingEquipmentEnum_BAT PredefinedCommonConductingEquipmentEnum = "BAT"
	PredefinedCommonConductingEquipmentEnum_BSH PredefinedCommonConductingEquipmentEnum = "BSH"
	PredefinedCommonConductingEquipmentEnum_CAB PredefinedCommonConductingEquipmentEnum = "CAB"
	PredefinedCommonConductingEquipmentEnum_GIL PredefinedCommonConductingEquipmentEnum = "GIL"
	PredefinedCommonConductingEquipmentEnum_LIN PredefinedCommonConductingEquipmentEnum = "LIN"
	PredefinedCommonConductingEquipmentEnum_RES PredefinedCommonConductingEquipmentEnum = "RES"
	PredefinedCommonConductingEquipmentEnum_RRC PredefinedCommonConductingEquipmentEnum = "RRC"
	PredefinedCommonConductingEquipmentEnum_SAR PredefinedCommonConductingEquipmentEnum = "SAR"
	PredefinedCommonConductingEquipmentEnum_TCF PredefinedCommonConductingEquipmentEnum = "TCF"
	PredefinedCommonConductingEquipmentEnum_TCR PredefinedCommonConductingEquipmentEnum = "TCR"
	PredefinedCommonConductingEquipmentEnum_IFL PredefinedCommonConductingEquipmentEnum = "IFL"
	PredefinedCommonConductingEquipmentEnum_FAN PredefinedCommonConductingEquipmentEnum = "FAN"
	PredefinedCommonConductingEquipmentEnum_SCR PredefinedCommonConductingEquipmentEnum = "SCR"
	PredefinedCommonConductingEquipmentEnum_SMC PredefinedCommonConductingEquipmentEnum = "SMC"
	PredefinedCommonConductingEquipmentEnum_PMP PredefinedCommonConductingEquipmentEnum = "PMP"
)

// PredefinedFCEnum is generated from xs:simpleType "tPredefinedFCEnum".
type PredefinedFCEnum string

const (
	PredefinedFCEnum_ST PredefinedFCEnum = "ST"
	PredefinedFCEnum_MX PredefinedFCEnum = "MX"
	PredefinedFCEnum_CO PredefinedFCEnum = "CO"
	PredefinedFCEnum_SP PredefinedFCEnum = "SP"
	PredefinedFCEnum_SG PredefinedFCEnum = "SG"
	PredefinedFCEnum_SE PredefinedFCEnum = "SE"
	PredefinedFCEnum_SV PredefinedFCEnum = "SV"
	PredefinedFCEnum_CF PredefinedFCEnum = "CF"
	PredefinedFCEnum_DC PredefinedFCEnum = "DC"
	PredefinedFCEnum_EX PredefinedFCEnum = "EX"
	PredefinedFCEnum_SR PredefinedFCEnum = "SR"
	PredefinedFCEnum_BL PredefinedFCEnum = "BL"
	PredefinedFCEnum_OR PredefinedFCEnum = "OR"
)

// PredefinedGeneralEquipmentEnum is generated from xs:simpleType "tPredefinedGeneralEquipmentEnum".
type PredefinedGeneralEquipmentEnum string

const (
	PredefinedGeneralEquipmentEnum_AXN PredefinedGeneralEquipmentEnum = "AXN"
	PredefinedGeneralEquipmentEnum_BAT PredefinedGeneralEquipmentEnum = "BAT"
	PredefinedGeneralEquipmentEnum_MOT PredefinedGeneralEquipmentEnum = "MOT"
	PredefinedGeneralEquipmentEnum_FAN PredefinedGeneralEquipmentEnum = "FAN"
	PredefinedGeneralEquipmentEnum_FIL PredefinedGeneralEquipmentEnum = "FIL"
	PredefinedGeneralEquipmentEnum_PMP PredefinedGeneralEquipmentEnum = "PMP"
	PredefinedGeneralEquipmentEnum_TNK PredefinedGeneralEquipmentEnum = "TNK"
	PredefinedGeneralEquipmentEnum_VLV PredefinedGeneralEquipmentEnum = "VLV"
)

// PredefinedPTypeEnum is generated from xs:simpleType "tPredefinedPTypeEnum".
type PredefinedPTypeEnum string

const (
	PredefinedPTypeEnum_IP                 PredefinedPTypeEnum = "IP"
	PredefinedPTypeEnum_IP_SUBNET          PredefinedPTypeEnum = "IP-SUBNET"
	PredefinedPTypeEnum_IP_GATEWAY         PredefinedPTypeEnum = "IP-GATEWAY"
	PredefinedPTypeEnum_OSI_NSAP           PredefinedPTypeEnum = "OSI-NSAP"
	PredefinedPTypeEnum_OSI_TSEL           PredefinedPTypeEnum = "OSI-TSEL"
	PredefinedPTypeEnum_OSI_SSEL           PredefinedPTypeEnum = "OSI-SSEL"
	PredefinedPTypeEnum_OSI_PSEL           PredefinedPTypeEnum = "OSI-PSEL"
	PredefinedPTypeEnum_OSI_AP_Title       PredefinedPTypeEnum = "OSI-AP-Title"
	PredefinedPTypeEnum_OSI_AP_Invoke      PredefinedPTypeEnum = "OSI-AP-Invoke"
	PredefinedPTypeEnum_OSI_AE_Qualifier   PredefinedPTypeEnum = "OSI-AE-Qualifier"
	PredefinedPTypeEnum_OSI_AE_Invoke      PredefinedPTypeEnum = "OSI-AE-Invoke"
	PredefinedPTypeEnum_MAC_Address        PredefinedPTypeEnum = "MAC-Address"
	PredefinedPTypeEnum_APPID              PredefinedPTypeEnum = "APPID"
	PredefinedPTypeEnum_VLAN_PRIORITY      PredefinedPTypeEnum = "VLAN-PRIORITY"
	PredefinedPTypeEnum_VLAN_ID            PredefinedPTypeEnum = "VLAN-ID"
	PredefinedPTypeEnum_SNTP_Port          PredefinedPTypeEnum = "SNTP-Port"
	PredefinedPTypeEnum_MMS_Port           PredefinedPTypeEnum = "MMS-Port"
	PredefinedPTypeEnum_DNSName            PredefinedPTypeEnum = "DNSName"
	PredefinedPTypeEnum_IPv6FlowLabel      PredefinedPTypeEnum = "IPv6FlowLabel"
	PredefinedPTypeEnum_IPv6ClassOfTraffic PredefinedPTypeEnum = "IPv6ClassOfTraffic"
	PredefinedPTypeEnum_C37_118_IP_Port    PredefinedPTypeEnum = "C37-118-IP-Port"
	PredefinedPTypeEnum_IP_UDP_PORT        PredefinedPTypeEnum = "IP-UDP-PORT"
	PredefinedPTypeEnum_IP_TCP_PORT        PredefinedPTypeEnum = "IP-TCP-PORT"
	PredefinedPTypeEnum_IPv6               PredefinedPTypeEnum = "IPv6"
	PredefinedPTypeEnum_IPv6_SUBNET        PredefinedPTypeEnum = "IPv6-SUBNET"
	PredefinedPTypeEnum_IPv6_GATEWAY       PredefinedPTypeEnum = "IPv6-GATEWAY"
	PredefinedPTypeEnum_IPv6_IGMPv3Src     PredefinedPTypeEnum = "IPv6-IGMPv3Src"
	PredefinedPTypeEnum_IP_IGMPv3Src       PredefinedPTypeEnum = "IP-IGMPv3Src"
	PredefinedPTypeEnum_IP_ClassOfTraffic  PredefinedPTypeEnum = "IP-ClassOfTraffic"
)

// PredefinedPTypePhysConnEnum is generated from xs:simpleType "tPredefinedPTypePhysConnEnum".
type PredefinedPTypePhysConnEnum string

const (
	PredefinedPTypePhysConnEnum_Type  PredefinedPTypePhysConnEnum = "Type"
	PredefinedPTypePhysConnEnum_Plug  PredefinedPTypePhysConnEnum = "Plug"
	PredefinedPTypePhysConnEnum_Cable PredefinedPTypePhysConnEnum = "Cable"
	PredefinedPTypePhysConnEnum_Port  PredefinedPTypePhysConnEnum = "Port"
)

// PredefinedPhysConnTypeEnum is generated from xs:simpleType "tPredefinedPhysConnTypeEnum".
type PredefinedPhysConnTypeEnum string

const (
	PredefinedPhysConnTypeEnum_Connection PredefinedPhysConnTypeEnum = "Connection"
	PredefinedPhysConnTypeEnum_RedConn    PredefinedPhysConnTypeEnum = "RedConn"
)

// PredefinedSCLFileType is generated from xs:simpleType "tPredefinedSCLFileType".
type PredefinedSCLFileType string

const (
	PredefinedSCLFileType_ICD PredefinedSCLFileType = "ICD"
	PredefinedSCLFileType_IID PredefinedSCLFileType = "IID"
	PredefinedSCLFileType_CID PredefinedSCLFileType = "CID"
	PredefinedSCLFileType_SSD PredefinedSCLFileType = "SSD"
	PredefinedSCLFileType_SCD PredefinedSCLFileType = "SCD"
	PredefinedSCLFileType_SED PredefinedSCLFileType = "SED"
)

// PredefinedTypeOfSecurityEnum is generated from xs:simpleType "tPredefinedTypeOfSecurityEnum".
type PredefinedTypeOfSecurityEnum string

const (
	PredefinedTypeOfSecurityEnum_None                   PredefinedTypeOfSecurityEnum = "None"
	PredefinedTypeOfSecurityEnum_Signature              PredefinedTypeOfSecurityEnum = "Signature"
	PredefinedTypeOfSecurityEnum_SignatureAndEncryption PredefinedTypeOfSecurityEnum = "SignatureAndEncryption"
)

// PredifinedSubnetTypes is generated from xs:simpleType "tPredifinedSubnetTypes".
type PredifinedSubnetTypes string

const (
	PredifinedSubnetTypes_V8_MMS  PredifinedSubnetTypes = "8-MMS"
	PredifinedSubnetTypes_V8_XMPP PredifinedSubnetTypes = "8-XMPP"
)

// RedProtEnum is generated from xs:simpleType "tRedProtEnum".
type RedProtEnum string

const (
	RedProtEnum_none RedProtEnum = "none"
	RedProtEnum_hsr  RedProtEnum = "hsr"
	RedProtEnum_prp  RedProtEnum = "prp"
	RedProtEnum_rstp RedProtEnum = "rstp"
)

// RightEnum is generated from xs:simpleType "tRightEnum".
type RightEnum string

const (
	RightEnum_full     RightEnum = "full"
	RightEnum_fix      RightEnum = "fix"
	RightEnum_dataflow RightEnum = "dataflow"
)

// SMVDeliveryEnum is generated from xs:simpleType "tSMVDeliveryEnum".
type SMVDeliveryEnum string

const (
	SMVDeliveryEnum_unicast   SMVDeliveryEnum = "unicast"
	SMVDeliveryEnum_multicast SMVDeliveryEnum = "multicast"
	SMVDeliveryEnum_both      SMVDeliveryEnum = "both"
)

// ServiceSettingsEnum is generated from xs:simpleType "tServiceSettingsEnum".
type ServiceSettingsEnum string

const (
	ServiceSettingsEnum_Dyn  ServiceSettingsEnum = "Dyn"
	ServiceSettingsEnum_Conf ServiceSettingsEnum = "Conf"
	ServiceSettingsEnum_Fix  ServiceSettingsEnum = "Fix"
)

// ServiceSettingsNoDynEnum is generated from xs:simpleType "tServiceSettingsNoDynEnum".
type ServiceSettingsNoDynEnum string

const (
	ServiceSettingsNoDynEnum_Conf ServiceSettingsNoDynEnum = "Conf"
	ServiceSettingsNoDynEnum_Fix  ServiceSettingsNoDynEnum = "Fix"
)

// ServiceType is generated from xs:simpleType "tServiceType".
type ServiceType string

const (
	ServiceType_Poll   ServiceType = "Poll"
	ServiceType_Report ServiceType = "Report"
	ServiceType_GOOSE  ServiceType = "GOOSE"
	ServiceType_SMV    ServiceType = "SMV"
)

// SmpMod is generated from xs:simpleType "tSmpMod".
type SmpMod string

const (
	SmpMod_SmpPerPeriod SmpMod = "SmpPerPeriod"
	SmpMod_SmpPerSec    SmpMod = "SmpPerSec"
	SmpMod_SecPerSmp    SmpMod = "SecPerSmp"
)

// SystemLNGroupEnum is generated from xs:simpleType "tSystemLNGroupEnum".
type SystemLNGroupEnum string

const (
	SystemLNGroupEnum_LLN0 SystemLNGroupEnum = "LLN0"
	SystemLNGroupEnum_LPHD SystemLNGroupEnum = "LPHD"
	SystemLNGroupEnum_LCCH SystemLNGroupEnum = "LCCH"
	SystemLNGroupEnum_LGOS SystemLNGroupEnum = "LGOS"
	SystemLNGroupEnum_LSVS SystemLNGroupEnum = "LSVS"
	SystemLNGroupEnum_LTIM SystemLNGroupEnum = "LTIM"
	SystemLNGroupEnum_LTMS SystemLNGroupEnum = "LTMS"
	SystemLNGroupEnum_LTRK SystemLNGroupEnum = "LTRK"
)

// TransformerWindingEnum is generated from xs:simpleType "tTransformerWindingEnum".
type TransformerWindingEnum string

const (
	TransformerWindingEnum_PTW TransformerWindingEnum = "PTW"
)

// UnitMultiplierEnum is generated from xs:simpleType "tUnitMultiplierEnum".
type UnitMultiplierEnum string

const (
	UnitMultiplierEnum_Unknown UnitMultiplierEnum = ""
	UnitMultiplierEnum_m       UnitMultiplierEnum = "m"
	UnitMultiplierEnum_k       UnitMultiplierEnum = "k"
	UnitMultiplierEnum_M       UnitMultiplierEnum = "M"
	UnitMultiplierEnum_mu      UnitMultiplierEnum = "mu"
	UnitMultiplierEnum_y       UnitMultiplierEnum = "y"
	UnitMultiplierEnum_z       UnitMultiplierEnum = "z"
	UnitMultiplierEnum_a       UnitMultiplierEnum = "a"
	UnitMultiplierEnum_f       UnitMultiplierEnum = "f"
	UnitMultiplierEnum_p       UnitMultiplierEnum = "p"
	UnitMultiplierEnum_n       UnitMultiplierEnum = "n"
	UnitMultiplierEnum_c       UnitMultiplierEnum = "c"
	UnitMultiplierEnum_d       UnitMultiplierEnum = "d"
	UnitMultiplierEnum_da      UnitMultiplierEnum = "da"
	UnitMultiplierEnum_h       UnitMultiplierEnum = "h"
	UnitMultiplierEnum_G       UnitMultiplierEnum = "G"
	UnitMultiplierEnum_T       UnitMultiplierEnum = "T"
	UnitMultiplierEnum_P       UnitMultiplierEnum = "P"
	UnitMultiplierEnum_E       UnitMultiplierEnum = "E"
	UnitMultiplierEnum_Z       UnitMultiplierEnum = "Z"
	UnitMultiplierEnum_Y       UnitMultiplierEnum = "Y"
)

// ValKindEnum is generated from xs:simpleType "tValKindEnum".
type ValKindEnum string

const (
	ValKindEnum_Spec ValKindEnum = "Spec"
	ValKindEnum_Conf ValKindEnum = "Conf"
	ValKindEnum_RO   ValKindEnum = "RO"
	ValKindEnum_Set  ValKindEnum = "Set"
)
