// SPDX-License-Identifier: MIT

package genir

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// Emitter generates Go source files from a resolved schema.
type Emitter struct {
	r       *Resolved
	outDir  string
	pkgName string

	// currentType tracks the type currently being emitted for
	// recursive type detection.
	currentType string
}

// NewEmitter creates a Go code emitter for the given resolved schema.
func NewEmitter(r *Resolved, outDir, pkgName string) *Emitter {
	return &Emitter{r: r, outDir: outDir, pkgName: pkgName}
}

// Emit generates all Go source files.
func (e *Emitter) Emit() error {
	if err := os.MkdirAll(e.outDir, 0o755); err != nil {
		return err
	}

	if err := e.emitDoc(); err != nil {
		return fmt.Errorf("emit doc.go: %w", err)
	}
	if err := e.emitEnums(); err != nil {
		return fmt.Errorf("emit enums.go: %w", err)
	}
	if err := e.emitTypes(); err != nil {
		return fmt.Errorf("emit types.go: %w", err)
	}
	if err := e.emitMetadata(); err != nil {
		return fmt.Errorf("emit metadata.go: %w", err)
	}
	return nil
}

func (e *Emitter) header() string {
	return fmt.Sprintf(`// Code generated by sclgen; DO NOT EDIT.
// Source bundle: %s
// Entry schema: SCL.xsd
`, e.r.Bundle)
}

func (e *Emitter) emitDoc() error {
	var b strings.Builder
	b.WriteString(e.header())
	fmt.Fprintf(&b, "\n// Package %s contains generated raw XML types for IEC 61850 SCL\n", e.pkgName)
	fmt.Fprintf(&b, "// schema version %s.\n", e.r.Version)
	fmt.Fprintf(&b, "//\n// Namespace: %s\n", e.r.Namespace)
	fmt.Fprintf(&b, "package %s\n", e.pkgName)
	return e.writeFile("doc.go", b.String())
}

func (e *Emitter) emitEnums() error {
	var enums []*SimpleType
	for _, st := range e.r.SimpleTypes {
		if IsEnumType(st) {
			enums = append(enums, st)
		}
	}
	sort.Slice(enums, func(i, j int) bool {
		return enums[i].Name < enums[j].Name
	})

	if len(enums) == 0 {
		return nil
	}

	var b strings.Builder
	b.WriteString(e.header())
	fmt.Fprintf(&b, "package %s\n", e.pkgName)

	for _, st := range enums {
		typeName := goTypeName(st.Name)
		fmt.Fprintf(&b, "\n// %s is generated from xs:simpleType %q.\n", typeName, st.Name)
		fmt.Fprintf(&b, "type %s string\n\n", typeName)
		fmt.Fprintf(&b, "const (\n")
		usedConsts := make(map[string]int)
		for _, val := range st.Enumerations {
			constName := goEnumConstName(typeName, val)
			if n, dup := usedConsts[constName]; dup {
				usedConsts[constName] = n + 1
				constName = fmt.Sprintf("%s_%d", constName, n+1)
			} else {
				usedConsts[constName] = 1
			}
			fmt.Fprintf(&b, "\t%s %s = %q\n", constName, typeName, val)
		}
		fmt.Fprintf(&b, ")\n")
	}

	return e.writeFile("enums.go", b.String())
}

func (e *Emitter) emitTypes() error {
	var b strings.Builder
	b.WriteString(e.header())
	fmt.Fprintf(&b, "package %s\n\n", e.pkgName)
	b.WriteString("import \"encoding/xml\"\n\n")

	// Sort complex types deterministically
	sorted := make([]*ComplexType, len(e.r.ComplexTypes))
	copy(sorted, e.r.ComplexTypes)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for _, ct := range sorted {
		if ct.Name == "" {
			continue
		}
		e.emitComplexType(&b, ct)
	}

	// Emit inline complex types that are referenced from elements
	e.emitInlineTypes(&b)

	// Emit the root SCL element
	for _, el := range e.r.TopElements {
		if el.Name == "SCL" && el.InlineComplex != nil {
			e.emitSCLRoot(&b, el)
		}
	}

	return e.writeFile("types.go", b.String())
}

func (e *Emitter) emitComplexType(b *strings.Builder, ct *ComplexType) {
	if ct.Abstract {
		return
	}

	typeName := goTypeName(ct.Name)

	if ct.Doc != "" {
		fmt.Fprintf(b, "// %s is generated from xs:complexType %q.\n", typeName, ct.Name)
	}

	isSimpleContent := ct.ContentKind == ContentSimpleExtend || ct.ContentKind == ContentSimpleRestrict

	if isSimpleContent {
		e.emitSimpleContentType(b, ct, typeName)
		return
	}

	e.currentType = typeName
	fmt.Fprintf(b, "type %s struct {\n", typeName)

	// Embed base type for extension (but not the abstract base types
	// which we flatten instead)
	allSeq := e.r.AllSequenceElements(ct)
	allAttrs := e.r.AllAttributes(ct)

	// Emit base class elements (flattened).
	// Track both XML names (for dedup) and Go names (for attr collision).
	seenXML := make(map[string]bool)
	seenGoNames := make(map[string]bool)
	for _, el := range allSeq {
		name := el.Name
		if el.Ref != "" {
			name = el.Ref
		}
		if seenXML[name] {
			continue
		}
		seenXML[name] = true
		seenGoNames[goFieldName(name)] = true
		e.emitField(b, el)
	}

	// Choice elements — inherit the choice's cardinality.
	if ct.Choice != nil {
		for _, el := range ct.Choice.Elements {
			name := el.Name
			if el.Ref != "" {
				name = el.Ref
			}
			if seenXML[name] {
				continue
			}
			seenXML[name] = true
			seenGoNames[goFieldName(name)] = true
			adjusted := *el
			if ct.Choice.MaxOccurs == -1 || ct.Choice.MaxOccurs > 1 {
				adjusted.MaxOccurs = ct.Choice.MaxOccurs
			}
			adjusted.MinOccurs = 0
			e.emitField(b, &adjusted)
		}
	}

	// xs:any capture
	if e.hasAnyElement(ct) {
		fmt.Fprintf(b, "\tExtraElements []xml.Token `xml:\",any\"`\n")
	}

	// Attributes — check for element name collisions
	seenAttrs := make(map[string]bool)
	for _, attr := range allAttrs {
		if attr.Name == "" || seenAttrs[attr.Name] {
			continue
		}
		seenAttrs[attr.Name] = true
		goName := goFieldName(attr.Name)
		if seenGoNames[goName] {
			e.emitAttrFieldWithSuffix(b, attr, "Attr")
		} else {
			seenGoNames[goName] = true
			e.emitAttrField(b, attr)
		}
	}

	// xs:anyAttribute
	if e.hasAnyAttr(ct) {
		fmt.Fprintf(b, "\tExtraAttrs []xml.Attr `xml:\",any,attr\"`\n")
	}

	fmt.Fprintf(b, "}\n\n")
}

func (e *Emitter) emitSimpleContentType(b *strings.Builder, ct *ComplexType, typeName string) {
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	goBase := xsdToGoType(ct.BaseType)
	fmt.Fprintf(b, "\tValue %s `xml:\",chardata\"`\n", goBase)

	allAttrs := e.r.AllAttributes(ct)
	for _, attr := range allAttrs {
		if attr.Name == "" {
			continue
		}
		e.emitAttrField(b, attr)
	}
	fmt.Fprintf(b, "}\n\n")
}

func (e *Emitter) emitInlineTypes(b *strings.Builder) {
	// Collect all inline complex types from all complex types and
	// top elements, then emit them as standalone types.
	type inlineEntry struct {
		name string
		ct   *ComplexType
	}
	var inlines []inlineEntry
	seen := make(map[string]bool)

	collectFromElements := func(elements []*Element) {
		for _, el := range elements {
			name := el.Name
			if el.Ref != "" {
				name = el.Ref
				if refEl, ok := e.r.ElementMap[el.Ref]; ok && refEl.InlineComplex != nil {
					ic := refEl.InlineComplex
					if isEmptyExtension(ic) && ic.BaseType != "" && !isBuiltinXSD(ic.BaseType) {
						if _, ok := e.r.ComplexTypeMap[ic.BaseType]; ok {
							continue
						}
					}
					goName := goTypeName(name) + "Inline"
					if !seen[goName] {
						seen[goName] = true
						inlines = append(inlines, inlineEntry{goName, refEl.InlineComplex})
					}
				}
				continue
			}
			if el.InlineComplex != nil {
				ic := el.InlineComplex
				if isEmptyExtension(ic) && ic.BaseType != "" && !isBuiltinXSD(ic.BaseType) {
					if _, ok := e.r.ComplexTypeMap[ic.BaseType]; ok {
						continue
					}
				}
				goName := goTypeName(name) + "Inline"
				if !seen[goName] {
					seen[goName] = true
					inlines = append(inlines, inlineEntry{goName, ic})
				}
			}
		}
	}

	for _, ct := range e.r.ComplexTypes {
		collectFromElements(ct.Sequence)
		if ct.Choice != nil {
			collectFromElements(ct.Choice.Elements)
		}
	}
	for _, el := range e.r.TopElements {
		if el.InlineComplex != nil {
			collectFromElements(el.InlineComplex.Sequence)
			if el.InlineComplex.Choice != nil {
				collectFromElements(el.InlineComplex.Choice.Elements)
			}
		}
	}

	sort.Slice(inlines, func(i, j int) bool {
		return inlines[i].name < inlines[j].name
	})

	for _, entry := range inlines {
		fmt.Fprintf(b, "type %s struct {\n", entry.name)
		for _, el := range entry.ct.Sequence {
			e.emitField(b, el)
		}
		allAttrs := e.r.ExpandedAttributes(entry.ct)
		for _, attr := range allAttrs {
			if attr.Name != "" {
				e.emitAttrField(b, attr)
			}
		}
		fmt.Fprintf(b, "}\n\n")
	}
}

func (e *Emitter) emitSCLRoot(b *strings.Builder, el *Element) {
	ct := el.InlineComplex

	e.currentType = "SCL"
	fmt.Fprintf(b, "// SCL is the root element of an IEC 61850 SCL document.\n")
	fmt.Fprintf(b, "type SCL struct {\n")
	fmt.Fprintf(b, "\tXMLName xml.Name `xml:\"%s SCL\"`\n", e.r.Namespace)

	allSeq := e.r.AllSequenceElements(ct)
	allAttrs := e.r.AllAttributes(ct)

	seenElements := make(map[string]bool)
	for _, sel := range allSeq {
		name := sel.Name
		if sel.Ref != "" {
			name = sel.Ref
		}
		if seenElements[name] {
			continue
		}
		seenElements[name] = true
		e.emitField(b, sel)
	}

	if ct.Choice != nil {
		for _, sel := range ct.Choice.Elements {
			name := sel.Name
			if sel.Ref != "" {
				name = sel.Ref
			}
			if seenElements[name] {
				continue
			}
			seenElements[name] = true
			e.emitField(b, sel)
		}
	}

	if e.hasAnyElement(ct) {
		fmt.Fprintf(b, "\tExtraElements []xml.Token `xml:\",any\"`\n")
	}

	seenAttrs := make(map[string]bool)
	for _, attr := range allAttrs {
		if attr.Name == "" || seenAttrs[attr.Name] {
			continue
		}
		seenAttrs[attr.Name] = true
		e.emitAttrField(b, attr)
	}

	if e.hasAnyAttr(ct) {
		fmt.Fprintf(b, "\tExtraAttrs []xml.Attr `xml:\",any,attr\"`\n")
	}

	fmt.Fprintf(b, "}\n\n")
}

func (e *Emitter) emitField(b *strings.Builder, el *Element) {
	fieldName := el.Name
	if el.Ref != "" {
		fieldName = el.Ref
	}
	goName := goFieldName(fieldName)

	typeName := e.resolveElementType(el)
	tag := fieldName

	isSlice := el.MaxOccurs == -1 || el.MaxOccurs > 1
	isOptional := el.MinOccurs == 0 && !isSlice

	var goType string
	if isSlice {
		if e.isRecursiveRef(typeName) {
			goType = "[]*" + typeName
		} else {
			goType = "[]" + typeName
		}
	} else if isOptional {
		goType = "*" + typeName
	} else {
		goType = typeName
	}

	omit := ""
	if el.MinOccurs == 0 {
		omit = ",omitempty"
	}

	fmt.Fprintf(b, "\t%s %s `xml:\"%s%s\"`\n", goName, goType, tag, omit)
}

func (e *Emitter) emitAttrField(b *strings.Builder, attr *Attribute) {
	e.emitAttrFieldWithSuffix(b, attr, "")
}

func (e *Emitter) emitAttrFieldWithSuffix(b *strings.Builder, attr *Attribute, suffix string) {
	goName := goFieldName(attr.Name) + suffix
	goType := e.resolveAttrType(attr)
	omit := ""
	if attr.Use != "required" {
		omit = ",omitempty"
	}
	fmt.Fprintf(b, "\t%s %s `xml:\"%s,attr%s\"`\n", goName, goType, attr.Name, omit)
}

// isRecursiveRef detects if the given Go type name is the same as
// the type currently being emitted (self-referential type).
func (e *Emitter) isRecursiveRef(goType string) bool {
	return goType == e.currentType
}

// isEmptyExtension returns true if the complex type is a pure
// extension with no own sequence, choice, or attribute content.
func isEmptyExtension(ct *ComplexType) bool {
	return (ct.ContentKind == ContentComplexExtend) &&
		len(ct.Sequence) == 0 &&
		ct.Choice == nil &&
		len(ct.Attributes) == 0 &&
		len(ct.AttrGroupRefs) == 0
}

func (e *Emitter) resolveElementType(el *Element) string {
	if el.InlineComplex != nil {
		ic := el.InlineComplex
		if isEmptyExtension(ic) && ic.BaseType != "" && !isBuiltinXSD(ic.BaseType) {
			if _, ok := e.r.ComplexTypeMap[ic.BaseType]; ok {
				return goTypeName(ic.BaseType)
			}
		}
		return goTypeName(el.Name) + "Inline"
	}

	typeName := el.Type
	if typeName == "" && el.Ref != "" {
		if refEl, ok := e.r.ElementMap[el.Ref]; ok {
			typeName = refEl.Type
			if typeName == "" && refEl.InlineComplex != nil {
				ic := refEl.InlineComplex
				if isEmptyExtension(ic) && ic.BaseType != "" && !isBuiltinXSD(ic.BaseType) {
					if _, ok := e.r.ComplexTypeMap[ic.BaseType]; ok {
						return goTypeName(ic.BaseType)
					}
				}
				return goTypeName(el.Ref) + "Inline"
			}
		}
	}

	if typeName == "" {
		return "string"
	}
	if isBuiltinXSD(typeName) {
		return xsdToGoType(typeName)
	}
	if _, ok := e.r.ComplexTypeMap[typeName]; ok {
		return goTypeName(typeName)
	}
	if st, ok := e.r.SimpleTypeMap[typeName]; ok {
		if IsEnumType(st) {
			return goTypeName(typeName)
		}
		return "string"
	}
	return "string"
}

func (e *Emitter) resolveAttrType(attr *Attribute) string {
	if attr.InlineSimple != nil {
		if IsEnumType(attr.InlineSimple) {
			return "string"
		}
		if attr.InlineSimple.Base != "" {
			return xsdToGoType(attr.InlineSimple.Base)
		}
		return "string"
	}
	if attr.Type == "" {
		return "string"
	}
	if isBuiltinXSD(attr.Type) {
		return xsdToGoType(attr.Type)
	}
	if st, ok := e.r.SimpleTypeMap[attr.Type]; ok {
		if IsEnumType(st) {
			return goTypeName(attr.Type)
		}
		if st.Base != "" && isBuiltinXSD(st.Base) {
			return xsdToGoType(st.Base)
		}
		return "string"
	}
	return "string"
}

func (e *Emitter) hasAnyElement(ct *ComplexType) bool {
	if ct.HasAnyElement {
		return true
	}
	for _, base := range e.r.BaseChain(ct) {
		if base.HasAnyElement {
			return true
		}
	}
	return false
}

func (e *Emitter) hasAnyAttr(ct *ComplexType) bool {
	if ct.HasAnyAttr {
		return true
	}
	for _, base := range e.r.BaseChain(ct) {
		if base.HasAnyAttr {
			return true
		}
	}
	return false
}

func (e *Emitter) emitMetadata() error {
	var b strings.Builder
	b.WriteString(e.header())
	fmt.Fprintf(&b, "package %s\n\n", e.pkgName)

	// Emit type registry
	b.WriteString("// TypeRegistry maps XSD type names to Go type names.\n")
	b.WriteString("var TypeRegistry = map[string]string{\n")

	sorted := make([]*ComplexType, 0, len(e.r.ComplexTypes))
	for _, ct := range e.r.ComplexTypes {
		if ct.Name != "" && !ct.Abstract {
			sorted = append(sorted, ct)
		}
	}
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})
	for _, ct := range sorted {
		fmt.Fprintf(&b, "\t%q: %q,\n", ct.Name, goTypeName(ct.Name))
	}
	b.WriteString("}\n\n")

	// Enum registry
	var enums []*SimpleType
	for _, st := range e.r.SimpleTypes {
		if IsEnumType(st) {
			enums = append(enums, st)
		}
	}
	sort.Slice(enums, func(i, j int) bool {
		return enums[i].Name < enums[j].Name
	})

	b.WriteString("// EnumRegistry maps XSD enum type names to their allowed values.\n")
	b.WriteString("var EnumRegistry = map[string][]string{\n")
	for _, st := range enums {
		fmt.Fprintf(&b, "\t%q: {", st.Name)
		for i, v := range st.Enumerations {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", v)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	return e.writeFile("metadata.go", b.String())
}

func (e *Emitter) writeFile(name, content string) error {
	formatted, err := format.Source([]byte(content))
	if err != nil {
		// Write unformatted for debugging, then return the error.
		path := filepath.Join(e.outDir, name)
		_ = os.WriteFile(path, []byte(content), 0o644)
		return fmt.Errorf("gofmt %s: %w", name, err)
	}
	path := filepath.Join(e.outDir, name)
	return os.WriteFile(path, formatted, 0o644)
}

// --- Naming helpers ---

func goTypeName(xsdName string) string {
	name := xsdName
	if strings.HasPrefix(name, "t") && len(name) > 1 && unicode.IsUpper(rune(name[1])) {
		name = name[1:]
	}
	return exportName(name)
}

func goFieldName(xmlName string) string {
	return exportName(xmlName)
}

func goEnumConstName(typeName, value string) string {
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_':
			b.WriteRune(r)
		case r == '-', r == '.', r == '/', r == ' ', r == '^':
			b.WriteRune('_')
		default:
			// Skip non-ASCII and other special characters
		}
	}
	clean := b.String()

	// Collapse multiple underscores
	for strings.Contains(clean, "__") {
		clean = strings.ReplaceAll(clean, "__", "_")
	}
	clean = strings.Trim(clean, "_")

	if clean == "" {
		clean = "Unknown"
	}

	if len(clean) > 0 && clean[0] >= '0' && clean[0] <= '9' {
		clean = "V" + clean
	}

	return typeName + "_" + clean
}

func exportName(s string) string {
	if s == "" {
		return s
	}
	r := strings.NewReplacer(
		"-", "_",
		".", "_",
		"/", "_",
		" ", "_",
	)
	s = r.Replace(s)

	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func xsdToGoType(xsdType string) string {
	switch xsdType {
	case "xs:string", "xs:normalizedString", "xs:token", "xs:Name",
		"xs:NCName", "xs:anyURI", "xs:language":
		return "string"
	case "xs:boolean":
		return "bool"
	case "xs:integer", "xs:int":
		return "int"
	case "xs:unsignedInt":
		return "uint32"
	case "xs:unsignedByte":
		return "uint8"
	case "xs:unsignedShort":
		return "uint16"
	case "xs:short":
		return "int16"
	case "xs:long":
		return "int64"
	case "xs:unsignedLong":
		return "uint64"
	case "xs:decimal", "xs:float":
		return "float64"
	case "xs:double":
		return "float64"
	case "xs:positiveInteger", "xs:nonNegativeInteger":
		return "int"
	default:
		return "string"
	}
}
