// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2009.SCL.2007B.full
// Entry schema: SCL.xsd

// Package v2007b contains generated raw XML types for IEC 61850 SCL
// schema version v2007b.
//
// Namespace: http://www.iec.ch/61850/2003/SCL
package v2007b
