// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2018.SCL.2007B4.full
// Entry schema: SCL.xsd

// Package v2007b4 contains generated raw XML types for IEC 61850 SCL
// schema version v2007b4.
//
// Namespace: http://www.iec.ch/61850/2003/SCL
package v2007b4
