// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2018.SCL.2007B4.full
// Entry schema: SCL.xsd
package v2007b4

import "encoding/xml"

type AccessControl struct {
	ExtraElements []xml.Token `xml:",any"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type AccessPoint struct {
	Text          *Text         `xml:"Text,omitempty"`
	Private       []Private     `xml:"Private,omitempty"`
	Services      *Services     `xml:"Services,omitempty"`
	GOOSESecurity []Certificate `xml:"GOOSESecurity,omitempty"`
	SMVSecurity   []Certificate `xml:"SMVSecurity,omitempty"`
	Server        *Server       `xml:"Server,omitempty"`
	LN            []LN          `xml:"LN,omitempty"`
	ServerAt      *ServerAt     `xml:"ServerAt,omitempty"`
	ExtraElements []xml.Token   `xml:",any"`
	Name          string        `xml:"name,attr"`
	Router        bool          `xml:"router,attr,omitempty"`
	Clock         bool          `xml:"clock,attr,omitempty"`
	Kdc           bool          `xml:"kdc,attr,omitempty"`
	Desc          string        `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr    `xml:",any,attr"`
}

type Address struct {
	P []P `xml:"P"`
}

type Association struct {
	Kind          AssociationKindEnum `xml:"kind,attr"`
	AssociationID string              `xml:"associationID,attr,omitempty"`
	Prefix        string              `xml:"prefix,attr,omitempty"`
	LnClass       string              `xml:"lnClass,attr"`
	LnInst        string              `xml:"lnInst,attr"`
}

type BDA struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	BType         string      `xml:"bType,attr"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Type          string      `xml:"type,attr,omitempty"`
	Count         string      `xml:"count,attr,omitempty"`
	ValImport     bool        `xml:"valImport,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Bay struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	PowerTransformer    []PowerTransformer    `xml:"PowerTransformer,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment,omitempty"`
	ConnectivityNode    []ConnectivityNode    `xml:"ConnectivityNode,omitempty"`
	Function            []Function            `xml:"Function,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type BitRateInMbPerSec struct {
	Value      float64            `xml:",chardata"`
	Unit       string             `xml:"unit,attr,omitempty"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type Cert struct {
	CommonName  string `xml:"commonName,attr"`
	IdHierarchy string `xml:"idHierarchy,attr"`
}

type Certificate struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Subject       Cert        `xml:"Subject"`
	IssuerName    Cert        `xml:"IssuerName"`
	ExtraElements []xml.Token `xml:",any"`
	XferNumber    uint32      `xml:"xferNumber,attr,omitempty"`
	SerialNumber  string      `xml:"serialNumber,attr"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ClientLN struct {
	ApRef   string `xml:"apRef,attr,omitempty"`
	Prefix  string `xml:"prefix,attr,omitempty"`
	LnClass string `xml:"lnClass,attr"`
	LnInst  string `xml:"lnInst,attr"`
}

type ClientServices struct {
	TimeSyncProt   *TimeSyncProt `xml:"TimeSyncProt,omitempty"`
	McSecurity     *McSecurity   `xml:"McSecurity,omitempty"`
	Goose          bool          `xml:"goose,attr,omitempty"`
	Gsse           bool          `xml:"gsse,attr,omitempty"`
	BufReport      bool          `xml:"bufReport,attr,omitempty"`
	UnbufReport    bool          `xml:"unbufReport,attr,omitempty"`
	ReadLog        bool          `xml:"readLog,attr,omitempty"`
	Sv             bool          `xml:"sv,attr,omitempty"`
	SupportsLdName bool          `xml:"supportsLdName,attr,omitempty"`
	MaxAttributes  uint32        `xml:"maxAttributes,attr,omitempty"`
	MaxReports     uint32        `xml:"maxReports,attr,omitempty"`
	MaxGOOSE       uint32        `xml:"maxGOOSE,attr,omitempty"`
	MaxSMV         uint32        `xml:"maxSMV,attr,omitempty"`
	RGOOSE         bool          `xml:"rGOOSE,attr,omitempty"`
	RSV            bool          `xml:"rSV,attr,omitempty"`
	NoIctBinding   bool          `xml:"noIctBinding,attr,omitempty"`
}

type CommProt struct {
	Ipv6 bool `xml:"ipv6,attr,omitempty"`
}

type Communication struct {
	Text          *Text        `xml:"Text,omitempty"`
	Private       []Private    `xml:"Private,omitempty"`
	SubNetwork    []SubNetwork `xml:"SubNetwork"`
	ExtraElements []xml.Token  `xml:",any"`
	Desc          string       `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr   `xml:",any,attr"`
}

type ConductingEquipment struct {
	Text          *Text          `xml:"Text,omitempty"`
	Private       []Private      `xml:"Private,omitempty"`
	LNode         []LNode        `xml:"LNode,omitempty"`
	Terminal      []Terminal     `xml:"Terminal,omitempty"`
	SubEquipment  []SubEquipment `xml:"SubEquipment,omitempty"`
	EqFunction    []EqFunction   `xml:"EqFunction,omitempty"`
	ExtraElements []xml.Token    `xml:",any"`
	Type          string         `xml:"type,attr"`
	Virtual       bool           `xml:"virtual,attr,omitempty"`
	Name          string         `xml:"name,attr"`
	Desc          string         `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr     `xml:",any,attr"`
}

type ConfLNs struct {
	FixPrefix bool `xml:"fixPrefix,attr,omitempty"`
	FixLnInst bool `xml:"fixLnInst,attr,omitempty"`
}

type ConnectedAP struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Address       *Address    `xml:"Address,omitempty"`
	GSE           []GSE       `xml:"GSE,omitempty"`
	SMV           []SMV       `xml:"SMV,omitempty"`
	PhysConn      []PhysConn  `xml:"PhysConn,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedName       string      `xml:"iedName,attr"`
	ApName        string      `xml:"apName,attr"`
	RedProt       RedProtEnum `xml:"redProt,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ConnectivityNode struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	LNode         []LNode     `xml:"LNode,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	PathName      string      `xml:"pathName,attr"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ControlWithIEDName struct {
	Text          *Text           `xml:"Text,omitempty"`
	Private       []Private       `xml:"Private,omitempty"`
	IEDName       []IEDNameInline `xml:"IEDName,omitempty"`
	ExtraElements []xml.Token     `xml:",any"`
	ConfRev       uint32          `xml:"confRev,attr,omitempty"`
	Name          string          `xml:"name,attr"`
	DatSet        string          `xml:"datSet,attr,omitempty"`
	Desc          string          `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr      `xml:",any,attr"`
}

type DA struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ProtNs        []ProtNs    `xml:"ProtNs,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Fc            FCEnum      `xml:"fc,attr"`
	Dchg          bool        `xml:"dchg,attr,omitempty"`
	Qchg          bool        `xml:"qchg,attr,omitempty"`
	Dupd          bool        `xml:"dupd,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	BType         string      `xml:"bType,attr"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Type          string      `xml:"type,attr,omitempty"`
	Count         string      `xml:"count,attr,omitempty"`
	ValImport     bool        `xml:"valImport,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DAI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	ValImport     bool        `xml:"valImport,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DAType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	BDA           []BDA       `xml:"BDA"`
	ProtNs        []ProtNs    `xml:"ProtNs,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DO struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Type          string      `xml:"type,attr"`
	AccessControl string      `xml:"accessControl,attr,omitempty"`
	Transient     bool        `xml:"transient,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DOI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDI           []SDI       `xml:"SDI,omitempty"`
	DAI           []DAI       `xml:"DAI,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	AccessControl string      `xml:"accessControl,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DOType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDO           []SDO       `xml:"SDO,omitempty"`
	DA            []DA        `xml:"DA,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	Cdc           string      `xml:"cdc,attr"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DataSet struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	FCDA          []FCDA      `xml:"FCDA,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DataTypeTemplates struct {
	LNodeType []LNodeType `xml:"LNodeType"`
	DOType    []DOType    `xml:"DOType"`
	DAType    []DAType    `xml:"DAType,omitempty"`
	EnumType  []EnumType  `xml:"EnumType,omitempty"`
}

type DurationInMilliSec struct {
	Value      float64            `xml:",chardata"`
	Unit       string             `xml:"unit,attr,omitempty"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type DurationInSec struct {
	Value      string             `xml:",chardata"`
	Unit       string             `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type EnumType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	EnumVal       []EnumVal   `xml:"EnumVal"`
	ExtraElements []xml.Token `xml:",any"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type EnumVal struct {
	Value string `xml:",chardata"`
	Ord   int    `xml:"ord,attr"`
	Desc  string `xml:"desc,attr,omitempty"`
}

type EqFunction struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	EqSubFunction    []EqSubFunction    `xml:"EqSubFunction,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Type             string             `xml:"type,attr,omitempty"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type EqSubFunction struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	EqSubFunction    []*EqSubFunction   `xml:"EqSubFunction,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Type             string             `xml:"type,attr,omitempty"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type ExtRef struct {
	IedName     string      `xml:"iedName,attr,omitempty"`
	LdInst      string      `xml:"ldInst,attr,omitempty"`
	Prefix      string      `xml:"prefix,attr,omitempty"`
	LnClass     string      `xml:"lnClass,attr,omitempty"`
	LnInst      string      `xml:"lnInst,attr,omitempty"`
	DoName      string      `xml:"doName,attr,omitempty"`
	DaName      string      `xml:"daName,attr,omitempty"`
	IntAddr     string      `xml:"intAddr,attr,omitempty"`
	ServiceType ServiceType `xml:"serviceType,attr,omitempty"`
	SrcLDInst   string      `xml:"srcLDInst,attr,omitempty"`
	SrcPrefix   string      `xml:"srcPrefix,attr,omitempty"`
	SrcLNClass  string      `xml:"srcLNClass,attr,omitempty"`
	SrcLNInst   string      `xml:"srcLNInst,attr,omitempty"`
	SrcCBName   string      `xml:"srcCBName,attr,omitempty"`
	PServT      ServiceType `xml:"pServT,attr,omitempty"`
	PLN         string      `xml:"pLN,attr,omitempty"`
	PDO         string      `xml:"pDO,attr,omitempty"`
	PDA         string      `xml:"pDA,attr,omitempty"`
	Desc        string      `xml:"desc,attr,omitempty"`
}

type FCDA struct {
	LdInst  string `xml:"ldInst,attr,omitempty"`
	Prefix  string `xml:"prefix,attr,omitempty"`
	LnClass string `xml:"lnClass,attr,omitempty"`
	LnInst  string `xml:"lnInst,attr,omitempty"`
	DoName  string `xml:"doName,attr,omitempty"`
	DaName  string `xml:"daName,attr,omitempty"`
	Fc      FCEnum `xml:"fc,attr"`
	Ix      uint32 `xml:"ix,attr,omitempty"`
}

type FileHandling struct {
	Mms  bool `xml:"mms,attr,omitempty"`
	Ftp  bool `xml:"ftp,attr,omitempty"`
	Ftps bool `xml:"ftps,attr,omitempty"`
}

type Function struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	SubFunction         []SubFunction         `xml:"SubFunction,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Type                string                `xml:"type,attr,omitempty"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type GOOSEcapabilities struct {
	FixedOffs bool   `xml:"fixedOffs,attr,omitempty"`
	Goose     bool   `xml:"goose,attr,omitempty"`
	RGOOSE    bool   `xml:"rGOOSE,attr,omitempty"`
	Max       uint32 `xml:"max,attr"`
}

type GSE struct {
	Text          *Text               `xml:"Text,omitempty"`
	Private       []Private           `xml:"Private,omitempty"`
	Address       *Address            `xml:"Address,omitempty"`
	MinTime       *DurationInMilliSec `xml:"MinTime,omitempty"`
	MaxTime       *DurationInMilliSec `xml:"MaxTime,omitempty"`
	ExtraElements []xml.Token         `xml:",any"`
	LdInst        string              `xml:"ldInst,attr"`
	CbName        string              `xml:"cbName,attr"`
	Desc          string              `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr          `xml:",any,attr"`
}

type GSEControl struct {
	Text           *Text                        `xml:"Text,omitempty"`
	Private        []Private                    `xml:"Private,omitempty"`
	IEDName        []IEDNameInline              `xml:"IEDName,omitempty"`
	Protocol       *Protocol                    `xml:"Protocol,omitempty"`
	ExtraElements  []xml.Token                  `xml:",any"`
	Type           GSEControlTypeEnum           `xml:"type,attr,omitempty"`
	AppID          string                       `xml:"appID,attr"`
	FixedOffs      bool                         `xml:"fixedOffs,attr,omitempty"`
	SecurityEnable PredefinedTypeOfSecurityEnum `xml:"securityEnable,attr,omitempty"`
	ConfRev        uint32                       `xml:"confRev,attr,omitempty"`
	Name           string                       `xml:"name,attr"`
	DatSet         string                       `xml:"datSet,attr,omitempty"`
	Desc           string                       `xml:"desc,attr,omitempty"`
	ExtraAttrs     []xml.Attr                   `xml:",any,attr"`
}

type GSESettings struct {
	McSecurity     *McSecurity              `xml:"McSecurity,omitempty"`
	AppID          ServiceSettingsEnum      `xml:"appID,attr,omitempty"`
	DataLabel      ServiceSettingsEnum      `xml:"dataLabel,attr,omitempty"`
	KdaParticipant bool                     `xml:"kdaParticipant,attr,omitempty"`
	CbName         ServiceSettingsNoDynEnum `xml:"cbName,attr,omitempty"`
	DatSet         ServiceSettingsEnum      `xml:"datSet,attr,omitempty"`
}

type GeneralEquipment struct {
	Text          *Text        `xml:"Text,omitempty"`
	Private       []Private    `xml:"Private,omitempty"`
	LNode         []LNode      `xml:"LNode,omitempty"`
	EqFunction    []EqFunction `xml:"EqFunction,omitempty"`
	ExtraElements []xml.Token  `xml:",any"`
	Type          string       `xml:"type,attr"`
	Virtual       bool         `xml:"virtual,attr,omitempty"`
	Name          string       `xml:"name,attr"`
	Desc          string       `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr   `xml:",any,attr"`
}

type Header struct {
	Text          *Text          `xml:"Text,omitempty"`
	History       *HistoryInline `xml:"History,omitempty"`
	Id            string         `xml:"id,attr"`
	Version       string         `xml:"version,attr,omitempty"`
	Revision      string         `xml:"revision,attr,omitempty"`
	ToolID        string         `xml:"toolID,attr,omitempty"`
	NameStructure string         `xml:"nameStructure,attr,omitempty"`
}

type Hitem struct {
	ExtraElements []xml.Token `xml:",any"`
	Version       string      `xml:"version,attr"`
	Revision      string      `xml:"revision,attr"`
	When          string      `xml:"when,attr"`
	Who           string      `xml:"who,attr,omitempty"`
	What          string      `xml:"what,attr,omitempty"`
	Why           string      `xml:"why,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type IED struct {
	Text                *Text         `xml:"Text,omitempty"`
	Private             []Private     `xml:"Private,omitempty"`
	Services            *Services     `xml:"Services,omitempty"`
	AccessPoint         []AccessPoint `xml:"AccessPoint"`
	KDC                 []KDC         `xml:"KDC,omitempty"`
	ExtraElements       []xml.Token   `xml:",any"`
	Name                string        `xml:"name,attr"`
	Type                string        `xml:"type,attr,omitempty"`
	Manufacturer        string        `xml:"manufacturer,attr,omitempty"`
	ConfigVersion       string        `xml:"configVersion,attr,omitempty"`
	OriginalSclVersion  string        `xml:"originalSclVersion,attr,omitempty"`
	OriginalSclRevision string        `xml:"originalSclRevision,attr,omitempty"`
	OriginalSclRelease  uint8         `xml:"originalSclRelease,attr,omitempty"`
	EngRight            RightEnum     `xml:"engRight,attr,omitempty"`
	Owner               string        `xml:"owner,attr,omitempty"`
	Desc                string        `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr    `xml:",any,attr"`
}

type Inputs struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtRef        []ExtRef    `xml:"ExtRef"`
	ExtraElements []xml.Token `xml:",any"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type KDC struct {
	IedName string `xml:"iedName,attr"`
	ApName  string `xml:"apName,attr"`
}

type LDevice struct {
	Text          *Text          `xml:"Text,omitempty"`
	Private       []Private      `xml:"Private,omitempty"`
	LN0           LN0            `xml:"LN0"`
	LN            []LN           `xml:"LN,omitempty"`
	AccessControl *AccessControl `xml:"AccessControl,omitempty"`
	ExtraElements []xml.Token    `xml:",any"`
	Inst          string         `xml:"inst,attr"`
	LdName        string         `xml:"ldName,attr,omitempty"`
	Desc          string         `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr     `xml:",any,attr"`
}

type LN struct {
	Text          *Text           `xml:"Text,omitempty"`
	Private       []Private       `xml:"Private,omitempty"`
	DataSet       []DataSet       `xml:"DataSet,omitempty"`
	ReportControl []ReportControl `xml:"ReportControl,omitempty"`
	LogControl    []LogControl    `xml:"LogControl,omitempty"`
	DOI           []DOI           `xml:"DOI,omitempty"`
	Inputs        *Inputs         `xml:"Inputs,omitempty"`
	Log           []Log           `xml:"Log,omitempty"`
	ExtraElements []xml.Token     `xml:",any"`
	Prefix        string          `xml:"prefix,attr,omitempty"`
	LnClass       string          `xml:"lnClass,attr"`
	Inst          string          `xml:"inst,attr"`
	LnType        string          `xml:"lnType,attr"`
	Desc          string          `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr      `xml:",any,attr"`
}

type LN0 struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	DataSet             []DataSet             `xml:"DataSet,omitempty"`
	ReportControl       []ReportControl       `xml:"ReportControl,omitempty"`
	LogControl          []LogControl          `xml:"LogControl,omitempty"`
	DOI                 []DOI                 `xml:"DOI,omitempty"`
	Inputs              *Inputs               `xml:"Inputs,omitempty"`
	Log                 []Log                 `xml:"Log,omitempty"`
	GSEControl          []GSEControl          `xml:"GSEControl,omitempty"`
	SampledValueControl []SampledValueControl `xml:"SampledValueControl,omitempty"`
	SettingControl      *SettingControl       `xml:"SettingControl,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	LnClass             string                `xml:"lnClass,attr"`
	Inst                string                `xml:"inst,attr"`
	LnType              string                `xml:"lnType,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type LNode struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedName       string      `xml:"iedName,attr,omitempty"`
	LdInst        string      `xml:"ldInst,attr,omitempty"`
	Prefix        string      `xml:"prefix,attr,omitempty"`
	LnClass       string      `xml:"lnClass,attr"`
	LnInst        string      `xml:"lnInst,attr,omitempty"`
	LnType        string      `xml:"lnType,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LNodeType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	DO            []DO        `xml:"DO"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	LnClass       string      `xml:"lnClass,attr"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Line struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	Function            []Function            `xml:"Function,omitempty"`
	Voltage             *Voltage              `xml:"Voltage,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment"`
	ConnectivityNode    []ConnectivityNode    `xml:"ConnectivityNode,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Type                string                `xml:"type,attr,omitempty"`
	NomFreq             float64               `xml:"nomFreq,attr,omitempty"`
	NumPhases           uint8                 `xml:"numPhases,attr,omitempty"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type Log struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LogControl struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	TrgOps        *TrgOps     `xml:"TrgOps,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	LdInst        string      `xml:"ldInst,attr,omitempty"`
	Prefix        string      `xml:"prefix,attr,omitempty"`
	LnClass       string      `xml:"lnClass,attr,omitempty"`
	LnInst        string      `xml:"lnInst,attr,omitempty"`
	LogName       string      `xml:"logName,attr"`
	LogEna        bool        `xml:"logEna,attr,omitempty"`
	ReasonCode    bool        `xml:"reasonCode,attr,omitempty"`
	BufTime       uint32      `xml:"bufTime,attr,omitempty"`
	IntgPd        uint32      `xml:"intgPd,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	DatSet        string      `xml:"datSet,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LogSettings struct {
	LogEna ServiceSettingsEnum      `xml:"logEna,attr,omitempty"`
	TrgOps ServiceSettingsEnum      `xml:"trgOps,attr,omitempty"`
	IntgPd ServiceSettingsEnum      `xml:"intgPd,attr,omitempty"`
	CbName ServiceSettingsNoDynEnum `xml:"cbName,attr,omitempty"`
	DatSet ServiceSettingsEnum      `xml:"datSet,attr,omitempty"`
}

type McSecurity struct {
	Signature  bool `xml:"signature,attr,omitempty"`
	Encryption bool `xml:"encryption,attr,omitempty"`
}

type P struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_APPID struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_C37_118_IP_Port struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_DNSName struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IP struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IP_ClassOfTraffic struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IP_GATEWAY struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IP_IGMPv3Src struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IP_SUBNET struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6 struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6_GATEWAY struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6_IGMPv3Src struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6_SUBNET struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6ClassOfTraffic struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_IPv6FlowLabel struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_MAC_Address struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_MMS_Port struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_AE_Invoke struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_AE_Qualifier struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_AP_Invoke struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_AP_Title struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_NSAP struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_PSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_SSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_OSI_TSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_PhysConn struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_SNTP_Port struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_TCP_Port struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_UDP_Port struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_VLAN_ID struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type P_VLAN_PRIORITY struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type PhysConn struct {
	Text          *Text        `xml:"Text,omitempty"`
	Private       []Private    `xml:"Private,omitempty"`
	P             []P_PhysConn `xml:"P,omitempty"`
	ExtraElements []xml.Token  `xml:",any"`
	Type          string       `xml:"type,attr"`
	Desc          string       `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr   `xml:",any,attr"`
}

type PowerTransformer struct {
	Text               *Text                `xml:"Text,omitempty"`
	Private            []Private            `xml:"Private,omitempty"`
	LNode              []LNode              `xml:"LNode,omitempty"`
	TransformerWinding []TransformerWinding `xml:"TransformerWinding"`
	SubEquipment       []SubEquipment       `xml:"SubEquipment,omitempty"`
	EqFunction         []EqFunction         `xml:"EqFunction,omitempty"`
	ExtraElements      []xml.Token          `xml:",any"`
	Type               PowerTransformerEnum `xml:"type,attr"`
	Virtual            bool                 `xml:"virtual,attr,omitempty"`
	Name               string               `xml:"name,attr"`
	Desc               string               `xml:"desc,attr,omitempty"`
	ExtraAttrs         []xml.Attr           `xml:",any,attr"`
}

type Private struct {
	InnerXML      string      `xml:",innerxml"`
	ExtraElements []xml.Token `xml:",any"`
	Type          string      `xml:"type,attr"`
	Source        string      `xml:"source,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Process struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	Function            []Function            `xml:"Function,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment,omitempty"`
	Substation          []Substation          `xml:"Substation,omitempty"`
	Line                []Line                `xml:"Line,omitempty"`
	Process             []*Process            `xml:"Process,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Type                string                `xml:"type,attr,omitempty"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type ProtNs struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr,omitempty"`
}

type Protocol struct {
	Value          string `xml:",chardata"`
	MustUnderstand bool   `xml:"mustUnderstand,attr"`
}

type RedProt struct {
	Hsr  bool `xml:"hsr,attr,omitempty"`
	Prp  bool `xml:"prp,attr,omitempty"`
	Rstp bool `xml:"rstp,attr,omitempty"`
}

type ReportControl struct {
	Text          *Text           `xml:"Text,omitempty"`
	Private       []Private       `xml:"Private,omitempty"`
	TrgOps        *TrgOps         `xml:"TrgOps,omitempty"`
	OptFields     OptFieldsInline `xml:"OptFields"`
	RptEnabled    *RptEnabled     `xml:"RptEnabled,omitempty"`
	ExtraElements []xml.Token     `xml:",any"`
	RptID         string          `xml:"rptID,attr,omitempty"`
	ConfRev       uint32          `xml:"confRev,attr"`
	Buffered      bool            `xml:"buffered,attr,omitempty"`
	BufTime       uint32          `xml:"bufTime,attr,omitempty"`
	Indexed       bool            `xml:"indexed,attr,omitempty"`
	IntgPd        uint32          `xml:"intgPd,attr,omitempty"`
	Name          string          `xml:"name,attr"`
	DatSet        string          `xml:"datSet,attr,omitempty"`
	Desc          string          `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr      `xml:",any,attr"`
}

type ReportSettings struct {
	RptID     ServiceSettingsEnum      `xml:"rptID,attr,omitempty"`
	OptFields ServiceSettingsEnum      `xml:"optFields,attr,omitempty"`
	BufTime   ServiceSettingsEnum      `xml:"bufTime,attr,omitempty"`
	TrgOps    ServiceSettingsEnum      `xml:"trgOps,attr,omitempty"`
	IntgPd    ServiceSettingsEnum      `xml:"intgPd,attr,omitempty"`
	ResvTms   bool                     `xml:"resvTms,attr,omitempty"`
	Owner     bool                     `xml:"owner,attr,omitempty"`
	CbName    ServiceSettingsNoDynEnum `xml:"cbName,attr,omitempty"`
	DatSet    ServiceSettingsEnum      `xml:"datSet,attr,omitempty"`
}

type RptEnabled struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ClientLN      []ClientLN  `xml:"ClientLN,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Max           uint32      `xml:"max,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SDI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDI           []*SDI      `xml:"SDI,omitempty"`
	DAI           []DAI       `xml:"DAI,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SDO struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Type          string      `xml:"type,attr"`
	Count         string      `xml:"count,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SMV struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Address       *Address    `xml:"Address,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	LdInst        string      `xml:"ldInst,attr"`
	CbName        string      `xml:"cbName,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SMVSettings struct {
	McSecurity        *McSecurity              `xml:"McSecurity,omitempty"`
	SmpRate           []string                 `xml:"SmpRate,omitempty"`
	SamplesPerSec     []string                 `xml:"SamplesPerSec,omitempty"`
	SecPerSamples     []string                 `xml:"SecPerSamples,omitempty"`
	SvID              ServiceSettingsEnum      `xml:"svID,attr,omitempty"`
	OptFields         ServiceSettingsEnum      `xml:"optFields,attr,omitempty"`
	SmpRateAttr       ServiceSettingsEnum      `xml:"smpRate,attr,omitempty"`
	SamplesPerSecAttr bool                     `xml:"samplesPerSec,attr,omitempty"`
	PdcTimeStamp      bool                     `xml:"pdcTimeStamp,attr,omitempty"`
	SynchSrcId        bool                     `xml:"synchSrcId,attr,omitempty"`
	NofASDU           ServiceSettingsNoDynEnum `xml:"nofASDU,attr,omitempty"`
	KdaParticipant    bool                     `xml:"kdaParticipant,attr,omitempty"`
	CbName            ServiceSettingsNoDynEnum `xml:"cbName,attr,omitempty"`
	DatSet            ServiceSettingsEnum      `xml:"datSet,attr,omitempty"`
}

type SMVsc struct {
	Delivery     SMVDeliveryEnum `xml:"delivery,attr,omitempty"`
	DeliveryConf bool            `xml:"deliveryConf,attr,omitempty"`
	Sv           bool            `xml:"sv,attr,omitempty"`
	RSV          bool            `xml:"rSV,attr,omitempty"`
	Max          uint32          `xml:"max,attr"`
}

type SampledValueControl struct {
	Text           *Text                        `xml:"Text,omitempty"`
	Private        []Private                    `xml:"Private,omitempty"`
	IEDName        []IEDNameInline              `xml:"IEDName,omitempty"`
	SmvOpts        SmvOptsInline                `xml:"SmvOpts"`
	Protocol       *Protocol                    `xml:"Protocol,omitempty"`
	ExtraElements  []xml.Token                  `xml:",any"`
	SmvID          string                       `xml:"smvID,attr"`
	Multicast      bool                         `xml:"multicast,attr,omitempty"`
	SmpRate        uint32                       `xml:"smpRate,attr"`
	NofASDU        uint32                       `xml:"nofASDU,attr"`
	SmpMod         SmpMod                       `xml:"smpMod,attr,omitempty"`
	SecurityEnable PredefinedTypeOfSecurityEnum `xml:"securityEnable,attr,omitempty"`
	ConfRev        uint32                       `xml:"confRev,attr,omitempty"`
	Name           string                       `xml:"name,attr"`
	DatSet         string                       `xml:"datSet,attr,omitempty"`
	Desc           string                       `xml:"desc,attr,omitempty"`
	ExtraAttrs     []xml.Attr                   `xml:",any,attr"`
}

type Server struct {
	Text           *Text                `xml:"Text,omitempty"`
	Private        []Private            `xml:"Private,omitempty"`
	Authentication AuthenticationInline `xml:"Authentication"`
	LDevice        []LDevice            `xml:"LDevice"`
	Association    []Association        `xml:"Association,omitempty"`
	ExtraElements  []xml.Token          `xml:",any"`
	Timeout        uint32               `xml:"timeout,attr,omitempty"`
	Desc           string               `xml:"desc,attr,omitempty"`
	ExtraAttrs     []xml.Attr           `xml:",any,attr"`
}

type ServerAt struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	ApName        string      `xml:"apName,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ServiceConfReportControl struct {
	BufMode string `xml:"bufMode,attr,omitempty"`
	BufConf bool   `xml:"bufConf,attr,omitempty"`
	MaxBuf  uint32 `xml:"maxBuf,attr,omitempty"`
	Max     uint32 `xml:"max,attr"`
}

type ServiceForConfDataSet struct {
	Modify        bool   `xml:"modify,attr,omitempty"`
	MaxAttributes uint32 `xml:"maxAttributes,attr,omitempty"`
	Max           uint32 `xml:"max,attr"`
}

type ServiceWithMax struct {
	Max uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndMaxAttributes struct {
	MaxAttributes uint32 `xml:"maxAttributes,attr,omitempty"`
	Max           uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndModify struct {
	Modify bool   `xml:"modify,attr,omitempty"`
	Max    uint32 `xml:"max,attr"`
}

type ServiceWithMaxNonZero struct {
	Max uint32 `xml:"max,attr"`
}

type ServiceWithOptionalMax struct {
	Max uint32 `xml:"max,attr,omitempty"`
}

type ServiceYesNo struct {
}

type Services struct {
	DynAssociation          *ServiceWithOptionalMax         `xml:"DynAssociation,omitempty"`
	SettingGroups           *SettingGroups                  `xml:"SettingGroups,omitempty"`
	GetDirectory            *ServiceYesNo                   `xml:"GetDirectory,omitempty"`
	GetDataObjectDefinition *ServiceYesNo                   `xml:"GetDataObjectDefinition,omitempty"`
	DataObjectDirectory     *ServiceYesNo                   `xml:"DataObjectDirectory,omitempty"`
	GetDataSetValue         *ServiceYesNo                   `xml:"GetDataSetValue,omitempty"`
	SetDataSetValue         *ServiceYesNo                   `xml:"SetDataSetValue,omitempty"`
	DataSetDirectory        *ServiceYesNo                   `xml:"DataSetDirectory,omitempty"`
	ConfDataSet             *ServiceForConfDataSet          `xml:"ConfDataSet,omitempty"`
	DynDataSet              *ServiceWithMaxAndMaxAttributes `xml:"DynDataSet,omitempty"`
	ReadWrite               *ServiceYesNo                   `xml:"ReadWrite,omitempty"`
	TimerActivatedControl   *ServiceYesNo                   `xml:"TimerActivatedControl,omitempty"`
	ConfReportControl       *ServiceConfReportControl       `xml:"ConfReportControl,omitempty"`
	GetCBValues             *ServiceYesNo                   `xml:"GetCBValues,omitempty"`
	ConfLogControl          *ServiceWithMaxNonZero          `xml:"ConfLogControl,omitempty"`
	ReportSettings          *ReportSettings                 `xml:"ReportSettings,omitempty"`
	LogSettings             *LogSettings                    `xml:"LogSettings,omitempty"`
	GSESettings             *GSESettings                    `xml:"GSESettings,omitempty"`
	SMVSettings             *SMVSettings                    `xml:"SMVSettings,omitempty"`
	GSEDir                  *ServiceYesNo                   `xml:"GSEDir,omitempty"`
	GOOSE                   *GOOSEcapabilities              `xml:"GOOSE,omitempty"`
	GSSE                    *ServiceWithMax                 `xml:"GSSE,omitempty"`
	SMVsc                   *SMVsc                          `xml:"SMVsc,omitempty"`
	FileHandling            *FileHandling                   `xml:"FileHandling,omitempty"`
	ConfLNs                 *ConfLNs                        `xml:"ConfLNs,omitempty"`
	ClientServices          *ClientServices                 `xml:"ClientServices,omitempty"`
	ConfLdName              *ServiceYesNo                   `xml:"ConfLdName,omitempty"`
	SupSubscription         *SupSubscription                `xml:"SupSubscription,omitempty"`
	ConfSigRef              *ServiceWithMaxNonZero          `xml:"ConfSigRef,omitempty"`
	ValueHandling           *ValueHandling                  `xml:"ValueHandling,omitempty"`
	RedProt                 *RedProt                        `xml:"RedProt,omitempty"`
	TimeSyncProt            *TimeSyncProt                   `xml:"TimeSyncProt,omitempty"`
	CommProt                *CommProt                       `xml:"CommProt,omitempty"`
	NameLength              string                          `xml:"nameLength,attr,omitempty"`
}

type SettingControl struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	NumOfSGs      uint32      `xml:"numOfSGs,attr"`
	ActSG         uint32      `xml:"actSG,attr,omitempty"`
	ResvTms       uint16      `xml:"resvTms,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SettingGroups struct {
	SGEdit *SGEditInline `xml:"SGEdit,omitempty"`
	ConfSG *ConfSGInline `xml:"ConfSG,omitempty"`
}

type SubEquipment struct {
	Text          *Text        `xml:"Text,omitempty"`
	Private       []Private    `xml:"Private,omitempty"`
	LNode         []LNode      `xml:"LNode,omitempty"`
	EqFunction    []EqFunction `xml:"EqFunction,omitempty"`
	ExtraElements []xml.Token  `xml:",any"`
	Phase         PhaseEnum    `xml:"phase,attr,omitempty"`
	Virtual       bool         `xml:"virtual,attr,omitempty"`
	Name          string       `xml:"name,attr"`
	Desc          string       `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr   `xml:",any,attr"`
}

type SubFunction struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment,omitempty"`
	SubFunction         []*SubFunction        `xml:"SubFunction,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Type                string                `xml:"type,attr,omitempty"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type SubNetwork struct {
	Text          *Text              `xml:"Text,omitempty"`
	Private       []Private          `xml:"Private,omitempty"`
	BitRate       *BitRateInMbPerSec `xml:"BitRate,omitempty"`
	ConnectedAP   []ConnectedAP      `xml:"ConnectedAP"`
	ExtraElements []xml.Token        `xml:",any"`
	Type          string             `xml:"type,attr,omitempty"`
	Name          string             `xml:"name,attr"`
	Desc          string             `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr         `xml:",any,attr"`
}

type Substation struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	PowerTransformer []PowerTransformer `xml:"PowerTransformer,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	VoltageLevel     []VoltageLevel     `xml:"VoltageLevel"`
	Function         []Function         `xml:"Function,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type SupSubscription struct {
	MaxGo uint32 `xml:"maxGo,attr"`
	MaxSv uint32 `xml:"maxSv,attr"`
}

type TapChanger struct {
	Text          *Text          `xml:"Text,omitempty"`
	Private       []Private      `xml:"Private,omitempty"`
	LNode         []LNode        `xml:"LNode,omitempty"`
	SubEquipment  []SubEquipment `xml:"SubEquipment,omitempty"`
	EqFunction    []EqFunction   `xml:"EqFunction,omitempty"`
	ExtraElements []xml.Token    `xml:",any"`
	Type          string         `xml:"type,attr"`
	Virtual       bool           `xml:"virtual,attr,omitempty"`
	Name          string         `xml:"name,attr"`
	Desc          string         `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr     `xml:",any,attr"`
}

type Terminal struct {
	Text             *Text       `xml:"Text,omitempty"`
	Private          []Private   `xml:"Private,omitempty"`
	ExtraElements    []xml.Token `xml:",any"`
	Name             string      `xml:"name,attr,omitempty"`
	ConnectivityNode string      `xml:"connectivityNode,attr"`
	ProcessName      string      `xml:"processName,attr,omitempty"`
	SubstationName   string      `xml:"substationName,attr,omitempty"`
	VoltageLevelName string      `xml:"voltageLevelName,attr,omitempty"`
	BayName          string      `xml:"bayName,attr,omitempty"`
	CNodeName        string      `xml:"cNodeName,attr"`
	LineName         string      `xml:"lineName,attr,omitempty"`
	Desc             string      `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr  `xml:",any,attr"`
}

type Text struct {
	ExtraElements []xml.Token `xml:",any"`
	Source        string      `xml:"source,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type TimeSyncProt struct {
	Sntp         bool `xml:"sntp,attr,omitempty"`
	Iec61850_9_3 bool `xml:"iec61850_9_3,attr,omitempty"`
	C37_238      bool `xml:"c37_238,attr,omitempty"`
	Other        bool `xml:"other,attr,omitempty"`
}

type TransformerWinding struct {
	Text          *Text                  `xml:"Text,omitempty"`
	Private       []Private              `xml:"Private,omitempty"`
	LNode         []LNode                `xml:"LNode,omitempty"`
	Terminal      []Terminal             `xml:"Terminal,omitempty"`
	SubEquipment  []SubEquipment         `xml:"SubEquipment,omitempty"`
	TapChanger    *TapChanger            `xml:"TapChanger,omitempty"`
	NeutralPoint  *Terminal              `xml:"NeutralPoint,omitempty"`
	EqFunction    []EqFunction           `xml:"EqFunction,omitempty"`
	ExtraElements []xml.Token            `xml:",any"`
	Type          TransformerWindingEnum `xml:"type,attr"`
	Virtual       bool                   `xml:"virtual,attr,omitempty"`
	Name          string                 `xml:"name,attr"`
	Desc          string                 `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr             `xml:",any,attr"`
}

type TrgOps struct {
	Dchg   bool `xml:"dchg,attr,omitempty"`
	Qchg   bool `xml:"qchg,attr,omitempty"`
	Dupd   bool `xml:"dupd,attr,omitempty"`
	Period bool `xml:"period,attr,omitempty"`
	Gi     bool `xml:"gi,attr,omitempty"`
}

type Val struct {
	Value  string `xml:",chardata"`
	SGroup uint32 `xml:"sGroup,attr,omitempty"`
}

type ValueHandling struct {
	SetToRO bool `xml:"setToRO,attr,omitempty"`
}

type ValueWithUnit struct {
	Value      float64            `xml:",chardata"`
	Unit       string             `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type Voltage struct {
	Value      string             `xml:",chardata"`
	Unit       string             `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type VoltageLevel struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	PowerTransformer []PowerTransformer `xml:"PowerTransformer,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	Voltage          *Voltage           `xml:"Voltage,omitempty"`
	Bay              []Bay              `xml:"Bay"`
	Function         []Function         `xml:"Function,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	NomFreq          float64            `xml:"nomFreq,attr,omitempty"`
	NumPhases        uint8              `xml:"numPhases,attr,omitempty"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type AuthenticationInline struct {
	None        bool `xml:"none,attr,omitempty"`
	Password    bool `xml:"password,attr,omitempty"`
	Weak        bool `xml:"weak,attr,omitempty"`
	Strong      bool `xml:"strong,attr,omitempty"`
	Certificate bool `xml:"certificate,attr,omitempty"`
}

type ConfSGInline struct {
	ResvTms bool `xml:"resvTms,attr,omitempty"`
}

type HistoryInline struct {
	Hitem []Hitem `xml:"Hitem"`
}

type IEDNameInline struct {
	ApRef   string `xml:"apRef,attr,omitempty"`
	LdInst  string `xml:"ldInst,attr,omitempty"`
	Prefix  string `xml:"prefix,attr,omitempty"`
	LnClass string `xml:"lnClass,attr,omitempty"`
	LnInst  string `xml:"lnInst,attr,omitempty"`
}

type OptFieldsInline struct {
	SeqNum     bool `xml:"seqNum,attr,omitempty"`
	TimeStamp  bool `xml:"timeStamp,attr,omitempty"`
	DataSet    bool `xml:"dataSet,attr,omitempty"`
	ReasonCode bool `xml:"reasonCode,attr,omitempty"`
	DataRef    bool `xml:"dataRef,attr,omitempty"`
	EntryID    bool `xml:"entryID,attr,omitempty"`
	ConfigRef  bool `xml:"configRef,attr,omitempty"`
	BufOvfl    bool `xml:"bufOvfl,attr,omitempty"`
}

type SGEditInline struct {
	ResvTms bool `xml:"resvTms,attr,omitempty"`
}

type SmvOptsInline struct {
	RefreshTime        bool `xml:"refreshTime,attr,omitempty"`
	SampleSynchronized bool `xml:"sampleSynchronized,attr,omitempty"`
	SampleRate         bool `xml:"sampleRate,attr,omitempty"`
	DataSet            bool `xml:"dataSet,attr,omitempty"`
	Security           bool `xml:"security,attr,omitempty"`
	Timestamp          bool `xml:"timestamp,attr,omitempty"`
	SynchSourceId      bool `xml:"synchSourceId,attr,omitempty"`
}

// SCL is the root element of an IEC 61850 SCL document.
type SCL struct {
	XMLName           xml.Name           `xml:"http://www.iec.ch/61850/2003/SCL SCL"`
	Text              *Text              `xml:"Text,omitempty"`
	Private           []Private          `xml:"Private,omitempty"`
	Header            Header             `xml:"Header"`
	Substation        []Substation       `xml:"Substation,omitempty"`
	Communication     *Communication     `xml:"Communication,omitempty"`
	IED               []IED              `xml:"IED,omitempty"`
	DataTypeTemplates *DataTypeTemplates `xml:"DataTypeTemplates,omitempty"`
	Line              []Line             `xml:"Line,omitempty"`
	Process           []Process          `xml:"Process,omitempty"`
	ExtraElements     []xml.Token        `xml:",any"`
	Version           string             `xml:"version,attr"`
	Revision          string             `xml:"revision,attr"`
	Release           uint8              `xml:"release,attr"`
	ExtraAttrs        []xml.Attr         `xml:",any,attr"`
}
