// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2003.SCL.1.7.full
// Entry schema: SCL.xsd

// Package v17 contains generated raw XML types for IEC 61850 SCL
// schema version v17.
//
// Namespace: http://www.iec.ch/61850/2003/SCL
package v17
