// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2003.SCL.1.7.full
// Entry schema: SCL.xsd
package v17

// AssociationKindEnum is generated from xs:simpleType "tAssociationKindEnum".
type AssociationKindEnum string

const (
	AssociationKindEnum_pre_established AssociationKindEnum = "pre-established"
	AssociationKindEnum_predefined      AssociationKindEnum = "predefined"
)

// AuthenticationEnum is generated from xs:simpleType "tAuthenticationEnum".
type AuthenticationEnum string

const (
	AuthenticationEnum_none        AuthenticationEnum = "none"
	AuthenticationEnum_password    AuthenticationEnum = "password"
	AuthenticationEnum_week        AuthenticationEnum = "week"
	AuthenticationEnum_strong      AuthenticationEnum = "strong"
	AuthenticationEnum_certificate AuthenticationEnum = "certificate"
)

// DomainLNGroupAEnum is generated from xs:simpleType "tDomainLNGroupAEnum".
type DomainLNGroupAEnum string

const (
	DomainLNGroupAEnum_ANCR DomainLNGroupAEnum = "ANCR"
	DomainLNGroupAEnum_ARCO DomainLNGroupAEnum = "ARCO"
	DomainLNGroupAEnum_ATCC DomainLNGroupAEnum = "ATCC"
	DomainLNGroupAEnum_AVCO DomainLNGroupAEnum = "AVCO"
)

// DomainLNGroupCEnum is generated from xs:simpleType "tDomainLNGroupCEnum".
type DomainLNGroupCEnum string

const (
	DomainLNGroupCEnum_CILO DomainLNGroupCEnum = "CILO"
	DomainLNGroupCEnum_CSWI DomainLNGroupCEnum = "CSWI"
	DomainLNGroupCEnum_CALH DomainLNGroupCEnum = "CALH"
	DomainLNGroupCEnum_CCGR DomainLNGroupCEnum = "CCGR"
	DomainLNGroupCEnum_CPOW DomainLNGroupCEnum = "CPOW"
)

// DomainLNGroupGEnum is generated from xs:simpleType "tDomainLNGroupGEnum".
type DomainLNGroupGEnum string

const (
	DomainLNGroupGEnum_GAPC DomainLNGroupGEnum = "GAPC"
	DomainLNGroupGEnum_GGIO DomainLNGroupGEnum = "GGIO"
	DomainLNGroupGEnum_GSAL DomainLNGroupGEnum = "GSAL"
)

// DomainLNGroupIEnum is generated from xs:simpleType "tDomainLNGroupIEnum".
type DomainLNGroupIEnum string

const (
	DomainLNGroupIEnum_IHMI DomainLNGroupIEnum = "IHMI"
	DomainLNGroupIEnum_IARC DomainLNGroupIEnum = "IARC"
	DomainLNGroupIEnum_ITCI DomainLNGroupIEnum = "ITCI"
	DomainLNGroupIEnum_ITMI DomainLNGroupIEnum = "ITMI"
)

// DomainLNGroupMEnum is generated from xs:simpleType "tDomainLNGroupMEnum".
type DomainLNGroupMEnum string

const (
	DomainLNGroupMEnum_MMXU DomainLNGroupMEnum = "MMXU"
	DomainLNGroupMEnum_MDIF DomainLNGroupMEnum = "MDIF"
	DomainLNGroupMEnum_MHAI DomainLNGroupMEnum = "MHAI"
	DomainLNGroupMEnum_MHAN DomainLNGroupMEnum = "MHAN"
	DomainLNGroupMEnum_MMTR DomainLNGroupMEnum = "MMTR"
	DomainLNGroupMEnum_MMXN DomainLNGroupMEnum = "MMXN"
	DomainLNGroupMEnum_MSQI DomainLNGroupMEnum = "MSQI"
	DomainLNGroupMEnum_MSTA DomainLNGroupMEnum = "MSTA"
)

// DomainLNGroupPEnum is generated from xs:simpleType "tDomainLNGroupPEnum".
type DomainLNGroupPEnum string

const (
	DomainLNGroupPEnum_PDIF DomainLNGroupPEnum = "PDIF"
	DomainLNGroupPEnum_PDIS DomainLNGroupPEnum = "PDIS"
	DomainLNGroupPEnum_PDIR DomainLNGroupPEnum = "PDIR"
	DomainLNGroupPEnum_PDOP DomainLNGroupPEnum = "PDOP"
	DomainLNGroupPEnum_PDUP DomainLNGroupPEnum = "PDUP"
	DomainLNGroupPEnum_PFRC DomainLNGroupPEnum = "PFRC"
	DomainLNGroupPEnum_PHAR DomainLNGroupPEnum = "PHAR"
	DomainLNGroupPEnum_PHIZ DomainLNGroupPEnum = "PHIZ"
	DomainLNGroupPEnum_PIOC DomainLNGroupPEnum = "PIOC"
	DomainLNGroupPEnum_PMRI DomainLNGroupPEnum = "PMRI"
	DomainLNGroupPEnum_PMSS DomainLNGroupPEnum = "PMSS"
	DomainLNGroupPEnum_POPF DomainLNGroupPEnum = "POPF"
	DomainLNGroupPEnum_PPAM DomainLNGroupPEnum = "PPAM"
	DomainLNGroupPEnum_PSCH DomainLNGroupPEnum = "PSCH"
	DomainLNGroupPEnum_PSDE DomainLNGroupPEnum = "PSDE"
	DomainLNGroupPEnum_PTEF DomainLNGroupPEnum = "PTEF"
	DomainLNGroupPEnum_PTOC DomainLNGroupPEnum = "PTOC"
	DomainLNGroupPEnum_PTOF DomainLNGroupPEnum = "PTOF"
	DomainLNGroupPEnum_PTOV DomainLNGroupPEnum = "PTOV"
	DomainLNGroupPEnum_PTRC DomainLNGroupPEnum = "PTRC"
	DomainLNGroupPEnum_PTTR DomainLNGroupPEnum = "PTTR"
	DomainLNGroupPEnum_PTUC DomainLNGroupPEnum = "PTUC"
	DomainLNGroupPEnum_PTUV DomainLNGroupPEnum = "PTUV"
	DomainLNGroupPEnum_PUPF DomainLNGroupPEnum = "PUPF"
	DomainLNGroupPEnum_PTUF DomainLNGroupPEnum = "PTUF"
	DomainLNGroupPEnum_PVOC DomainLNGroupPEnum = "PVOC"
	DomainLNGroupPEnum_PVPH DomainLNGroupPEnum = "PVPH"
	DomainLNGroupPEnum_PZSU DomainLNGroupPEnum = "PZSU"
)

// DomainLNGroupREnum is generated from xs:simpleType "tDomainLNGroupREnum".
type DomainLNGroupREnum string

const (
	DomainLNGroupREnum_RSYN DomainLNGroupREnum = "RSYN"
	DomainLNGroupREnum_RDRE DomainLNGroupREnum = "RDRE"
	DomainLNGroupREnum_RADR DomainLNGroupREnum = "RADR"
	DomainLNGroupREnum_RBDR DomainLNGroupREnum = "RBDR"
	DomainLNGroupREnum_RDRS DomainLNGroupREnum = "RDRS"
	DomainLNGroupREnum_RBRF DomainLNGroupREnum = "RBRF"
	DomainLNGroupREnum_RDIR DomainLNGroupREnum = "RDIR"
	DomainLNGroupREnum_RFLO DomainLNGroupREnum = "RFLO"
	DomainLNGroupREnum_RPSB DomainLNGroupREnum = "RPSB"
	DomainLNGroupREnum_RREC DomainLNGroupREnum = "RREC"
)

// DomainLNGroupSEnum is generated from xs:simpleType "tDomainLNGroupSEnum".
type DomainLNGroupSEnum string

const (
	DomainLNGroupSEnum_SARC DomainLNGroupSEnum = "SARC"
	DomainLNGroupSEnum_SIMG DomainLNGroupSEnum = "SIMG"
	DomainLNGroupSEnum_SIML DomainLNGroupSEnum = "SIML"
	DomainLNGroupSEnum_SPDC DomainLNGroupSEnum = "SPDC"
)

// DomainLNGroupTEnum is generated from xs:simpleType "tDomainLNGroupTEnum".
type DomainLNGroupTEnum string

const (
	DomainLNGroupTEnum_TCTR DomainLNGroupTEnum = "TCTR"
	DomainLNGroupTEnum_TVTR DomainLNGroupTEnum = "TVTR"
)

// DomainLNGroupXEnum is generated from xs:simpleType "tDomainLNGroupXEnum".
type DomainLNGroupXEnum string

const (
	DomainLNGroupXEnum_XCBR DomainLNGroupXEnum = "XCBR"
	DomainLNGroupXEnum_XSWI DomainLNGroupXEnum = "XSWI"
)

// DomainLNGroupYEnum is generated from xs:simpleType "tDomainLNGroupYEnum".
type DomainLNGroupYEnum string

const (
	DomainLNGroupYEnum_YPTR DomainLNGroupYEnum = "YPTR"
	DomainLNGroupYEnum_YEFN DomainLNGroupYEnum = "YEFN"
	DomainLNGroupYEnum_YLTC DomainLNGroupYEnum = "YLTC"
	DomainLNGroupYEnum_YPSH DomainLNGroupYEnum = "YPSH"
)

// DomainLNGroupZEnum is generated from xs:simpleType "tDomainLNGroupZEnum".
type DomainLNGroupZEnum string

const (
	DomainLNGroupZEnum_ZAXN DomainLNGroupZEnum = "ZAXN"
	DomainLNGroupZEnum_ZBAT DomainLNGroupZEnum = "ZBAT"
	DomainLNGroupZEnum_ZBSH DomainLNGroupZEnum = "ZBSH"
	DomainLNGroupZEnum_ZCAB DomainLNGroupZEnum = "ZCAB"
	DomainLNGroupZEnum_ZCAP DomainLNGroupZEnum = "ZCAP"
	DomainLNGroupZEnum_ZCON DomainLNGroupZEnum = "ZCON"
	DomainLNGroupZEnum_ZGEN DomainLNGroupZEnum = "ZGEN"
	DomainLNGroupZEnum_ZGIL DomainLNGroupZEnum = "ZGIL"
	DomainLNGroupZEnum_ZLIN DomainLNGroupZEnum = "ZLIN"
	DomainLNGroupZEnum_ZMOT DomainLNGroupZEnum = "ZMOT"
	DomainLNGroupZEnum_ZREA DomainLNGroupZEnum = "ZREA"
	DomainLNGroupZEnum_ZRRC DomainLNGroupZEnum = "ZRRC"
	DomainLNGroupZEnum_ZSAR DomainLNGroupZEnum = "ZSAR"
	DomainLNGroupZEnum_ZTCF DomainLNGroupZEnum = "ZTCF"
	DomainLNGroupZEnum_ZTCR DomainLNGroupZEnum = "ZTCR"
)

// FCEnum is generated from xs:simpleType "tFCEnum".
type FCEnum string

const (
	FCEnum_ST FCEnum = "ST"
	FCEnum_MX FCEnum = "MX"
	FCEnum_CO FCEnum = "CO"
	FCEnum_SP FCEnum = "SP"
	FCEnum_SG FCEnum = "SG"
	FCEnum_SE FCEnum = "SE"
	FCEnum_SV FCEnum = "SV"
	FCEnum_CF FCEnum = "CF"
	FCEnum_DC FCEnum = "DC"
	FCEnum_EX FCEnum = "EX"
)

// GSEControlTypeEnum is generated from xs:simpleType "tGSEControlTypeEnum".
type GSEControlTypeEnum string

const (
	GSEControlTypeEnum_GSSE  GSEControlTypeEnum = "GSSE"
	GSEControlTypeEnum_GOOSE GSEControlTypeEnum = "GOOSE"
)

// LLN0Enum is generated from xs:simpleType "tLLN0Enum".
type LLN0Enum string

const (
	LLN0Enum_LLN0 LLN0Enum = "LLN0"
)

// LPHDEnum is generated from xs:simpleType "tLPHDEnum".
type LPHDEnum string

const (
	LPHDEnum_LPHD LPHDEnum = "LPHD"
)

// PhaseEnum is generated from xs:simpleType "tPhaseEnum".
type PhaseEnum string

const (
	PhaseEnum_A    PhaseEnum = "A"
	PhaseEnum_B    PhaseEnum = "B"
	PhaseEnum_C    PhaseEnum = "C"
	PhaseEnum_N    PhaseEnum = "N"
	PhaseEnum_all  PhaseEnum = "all"
	PhaseEnum_none PhaseEnum = "none"
)

// PowerTransformerEnum is generated from xs:simpleType "tPowerTransformerEnum".
type PowerTransformerEnum string

const (
	PowerTransformerEnum_PTR PowerTransformerEnum = "PTR"
)

// PredefinedAttributeNameEnum is generated from xs:simpleType "tPredefinedAttributeNameEnum".
type PredefinedAttributeNameEnum string

const (
	PredefinedAttributeNameEnum_T      PredefinedAttributeNameEnum = "T"
	PredefinedAttributeNameEnum_Test   PredefinedAttributeNameEnum = "Test"
	PredefinedAttributeNameEnum_Check  PredefinedAttributeNameEnum = "Check"
	PredefinedAttributeNameEnum_SIUnit PredefinedAttributeNameEnum = "SIUnit"
	PredefinedAttributeNameEnum_Oper   PredefinedAttributeNameEnum = "Oper"
	PredefinedAttributeNameEnum_SBO    PredefinedAttributeNameEnum = "SBO"
	PredefinedAttributeNameEnum_SBOw   PredefinedAttributeNameEnum = "SBOw"
	PredefinedAttributeNameEnum_Cancel PredefinedAttributeNameEnum = "Cancel"
)

// PredefinedBasicTypeEnum is generated from xs:simpleType "tPredefinedBasicTypeEnum".
type PredefinedBasicTypeEnum string

const (
	PredefinedBasicTypeEnum_BOOLEAN      PredefinedBasicTypeEnum = "BOOLEAN"
	PredefinedBasicTypeEnum_INT8         PredefinedBasicTypeEnum = "INT8"
	PredefinedBasicTypeEnum_INT16        PredefinedBasicTypeEnum = "INT16"
	PredefinedBasicTypeEnum_INT24        PredefinedBasicTypeEnum = "INT24"
	PredefinedBasicTypeEnum_INT32        PredefinedBasicTypeEnum = "INT32"
	PredefinedBasicTypeEnum_INT128       PredefinedBasicTypeEnum = "INT128"
	PredefinedBasicTypeEnum_INT8U        PredefinedBasicTypeEnum = "INT8U"
	PredefinedBasicTypeEnum_INT16U       PredefinedBasicTypeEnum = "INT16U"
	PredefinedBasicTypeEnum_INT24U       PredefinedBasicTypeEnum = "INT24U"
	PredefinedBasicTypeEnum_INT32U       PredefinedBasicTypeEnum = "INT32U"
	PredefinedBasicTypeEnum_FLOAT32      PredefinedBasicTypeEnum = "FLOAT32"
	PredefinedBasicTypeEnum_FLOAT64      PredefinedBasicTypeEnum = "FLOAT64"
	PredefinedBasicTypeEnum_Enum         PredefinedBasicTypeEnum = "Enum"
	PredefinedBasicTypeEnum_Dbpos        PredefinedBasicTypeEnum = "Dbpos"
	PredefinedBasicTypeEnum_Tcmd         PredefinedBasicTypeEnum = "Tcmd"
	PredefinedBasicTypeEnum_Quality      PredefinedBasicTypeEnum = "Quality"
	PredefinedBasicTypeEnum_Timestamp    PredefinedBasicTypeEnum = "Timestamp"
	PredefinedBasicTypeEnum_VisString32  PredefinedBasicTypeEnum = "VisString32"
	PredefinedBasicTypeEnum_VisString64  PredefinedBasicTypeEnum = "VisString64"
	PredefinedBasicTypeEnum_VisString129 PredefinedBasicTypeEnum = "VisString129"
	PredefinedBasicTypeEnum_VisString255 PredefinedBasicTypeEnum = "VisString255"
	PredefinedBasicTypeEnum_Octet64      PredefinedBasicTypeEnum = "Octet64"
	PredefinedBasicTypeEnum_Struct       PredefinedBasicTypeEnum = "Struct"
	PredefinedBasicTypeEnum_EntryTime    PredefinedBasicTypeEnum = "EntryTime"
	PredefinedBasicTypeEnum_Unicode255   PredefinedBasicTypeEnum = "Unicode255"
	PredefinedBasicTypeEnum_Check        PredefinedBasicTypeEnum = "Check"
)

// PredefinedCDCEnum is generated from xs:simpleType "tPredefinedCDCEnum".
type PredefinedCDCEnum string

const (
	PredefinedCDCEnum_SPS   PredefinedCDCEnum = "SPS"
	PredefinedCDCEnum_DPS   PredefinedCDCEnum = "DPS"
	PredefinedCDCEnum_INS   PredefinedCDCEnum = "INS"
	PredefinedCDCEnum_ACT   PredefinedCDCEnum = "ACT"
	PredefinedCDCEnum_ACD   PredefinedCDCEnum = "ACD"
	PredefinedCDCEnum_SEC   PredefinedCDCEnum = "SEC"
	PredefinedCDCEnum_BCR   PredefinedCDCEnum = "BCR"
	PredefinedCDCEnum_MV    PredefinedCDCEnum = "MV"
	PredefinedCDCEnum_CMV   PredefinedCDCEnum = "CMV"
	PredefinedCDCEnum_SAV   PredefinedCDCEnum = "SAV"
	PredefinedCDCEnum_WYE   PredefinedCDCEnum = "WYE"
	PredefinedCDCEnum_DEL   PredefinedCDCEnum = "DEL"
	PredefinedCDCEnum_SEQ   PredefinedCDCEnum = "SEQ"
	PredefinedCDCEnum_HMV   PredefinedCDCEnum = "HMV"
	PredefinedCDCEnum_HWYE  PredefinedCDCEnum = "HWYE"
	PredefinedCDCEnum_HDEL  PredefinedCDCEnum = "HDEL"
	PredefinedCDCEnum_SPC   PredefinedCDCEnum = "SPC"
	PredefinedCDCEnum_DPC   PredefinedCDCEnum = "DPC"
	PredefinedCDCEnum_INC   PredefinedCDCEnum = "INC"
	PredefinedCDCEnum_BSC   PredefinedCDCEnum = "BSC"
	PredefinedCDCEnum_ISC   PredefinedCDCEnum = "ISC"
	PredefinedCDCEnum_APC   PredefinedCDCEnum = "APC"
	PredefinedCDCEnum_SPG   PredefinedCDCEnum = "SPG"
	PredefinedCDCEnum_ING   PredefinedCDCEnum = "ING"
	PredefinedCDCEnum_ASG   PredefinedCDCEnum = "ASG"
	PredefinedCDCEnum_CURVE PredefinedCDCEnum = "CURVE"
	PredefinedCDCEnum_DPL   PredefinedCDCEnum = "DPL"
	PredefinedCDCEnum_LPL   PredefinedCDCEnum = "LPL"
	PredefinedCDCEnum_CSD   PredefinedCDCEnum = "CSD"
)

// PredefinedCommonConductingEquipmentEnum is generated from xs:simpleType "tPredefinedCommonConductingEquipmentEnum".
type PredefinedCommonConductingEquipmentEnum string

const (
	PredefinedCommonConductingEquipmentEnum_CBR PredefinedCommonConductingEquipmentEnum = "CBR"
	PredefinedCommonConductingEquipmentEnum_DIS PredefinedCommonConductingEquipmentEnum = "DIS"
	PredefinedCommonConductingEquipmentEnum_VTR PredefinedCommonConductingEquipmentEnum = "VTR"
	PredefinedCommonConductingEquipmentEnum_CTR PredefinedCommonConductingEquipmentEnum = "CTR"
	PredefinedCommonConductingEquipmentEnum_GEN PredefinedCommonConductingEquipmentEnum = "GEN"
	PredefinedCommonConductingEquipmentEnum_CAP PredefinedCommonConductingEquipmentEnum = "CAP"
	PredefinedCommonConductingEquipmentEnum_REA PredefinedCommonConductingEquipmentEnum = "REA"
	PredefinedCommonConductingEquipmentEnum_CON PredefinedCommonConductingEquipmentEnum = "CON"
	PredefinedCommonConductingEquipmentEnum_MOT PredefinedCommonConductingEquipmentEnum = "MOT"
	PredefinedCommonConductingEquipmentEnum_EFN PredefinedCommonConductingEquipmentEnum = "EFN"
	PredefinedCommonConductingEquipmentEnum_PSH PredefinedCommonConductingEquipmentEnum = "PSH"
	PredefinedCommonConductingEquipmentEnum_BAT PredefinedCommonConductingEquipmentEnum = "BAT"
	PredefinedCommonConductingEquipmentEnum_BSH PredefinedCommonConductingEquipmentEnum = "BSH"
	PredefinedCommonConductingEquipmentEnum_CAB PredefinedCommonConductingEquipmentEnum = "CAB"
	PredefinedCommonConductingEquipmentEnum_GIL PredefinedCommonConductingEquipmentEnum = "GIL"
	PredefinedCommonConductingEquipmentEnum_LIN PredefinedCommonConductingEquipmentEnum = "LIN"
	PredefinedCommonConductingEquipmentEnum_RRC PredefinedCommonConductingEquipmentEnum = "RRC"
	PredefinedCommonConductingEquipmentEnum_SAR PredefinedCommonConductingEquipmentEnum = "SAR"
	PredefinedCommonConductingEquipmentEnum_TCF PredefinedCommonConductingEquipmentEnum = "TCF"
	PredefinedCommonConductingEquipmentEnum_TCR PredefinedCommonConductingEquipmentEnum = "TCR"
	PredefinedCommonConductingEquipmentEnum_IFL PredefinedCommonConductingEquipmentEnum = "IFL"
)

// PredefinedGeneralEquipmentEnum is generated from xs:simpleType "tPredefinedGeneralEquipmentEnum".
type PredefinedGeneralEquipmentEnum string

const (
	PredefinedGeneralEquipmentEnum_AXN PredefinedGeneralEquipmentEnum = "AXN"
	PredefinedGeneralEquipmentEnum_BAT PredefinedGeneralEquipmentEnum = "BAT"
	PredefinedGeneralEquipmentEnum_MOT PredefinedGeneralEquipmentEnum = "MOT"
)

// PredefinedPTypeEnum is generated from xs:simpleType "tPredefinedPTypeEnum".
type PredefinedPTypeEnum string

const (
	PredefinedPTypeEnum_IP               PredefinedPTypeEnum = "IP"
	PredefinedPTypeEnum_IP_SUBNET        PredefinedPTypeEnum = "IP-SUBNET"
	PredefinedPTypeEnum_IP_GATEWAY       PredefinedPTypeEnum = "IP-GATEWAY"
	PredefinedPTypeEnum_OSI_NSAP         PredefinedPTypeEnum = "OSI-NSAP"
	PredefinedPTypeEnum_OSI_TSEL         PredefinedPTypeEnum = "OSI-TSEL"
	PredefinedPTypeEnum_OSI_SSEL         PredefinedPTypeEnum = "OSI-SSEL"
	PredefinedPTypeEnum_OSI_PSEL         PredefinedPTypeEnum = "OSI-PSEL"
	PredefinedPTypeEnum_OSI_AP_Title     PredefinedPTypeEnum = "OSI-AP-Title"
	PredefinedPTypeEnum_OSI_AP_Invoke    PredefinedPTypeEnum = "OSI-AP-Invoke"
	PredefinedPTypeEnum_OSI_AE_Qualifier PredefinedPTypeEnum = "OSI-AE-Qualifier"
	PredefinedPTypeEnum_OSI_AE_Invoke    PredefinedPTypeEnum = "OSI-AE-Invoke"
	PredefinedPTypeEnum_MAC_Address      PredefinedPTypeEnum = "MAC-Address"
	PredefinedPTypeEnum_APPID            PredefinedPTypeEnum = "APPID"
	PredefinedPTypeEnum_VLAN_PRIORITY    PredefinedPTypeEnum = "VLAN-PRIORITY"
	PredefinedPTypeEnum_VLAN_ID          PredefinedPTypeEnum = "VLAN-ID"
)

// SIUnitEnum is generated from xs:simpleType "tSIUnitEnum".
type SIUnitEnum string

const (
	SIUnitEnum_none    SIUnitEnum = "none"
	SIUnitEnum_m       SIUnitEnum = "m"
	SIUnitEnum_kg      SIUnitEnum = "kg"
	SIUnitEnum_s       SIUnitEnum = "s"
	SIUnitEnum_A       SIUnitEnum = "A"
	SIUnitEnum_K       SIUnitEnum = "K"
	SIUnitEnum_mol     SIUnitEnum = "mol"
	SIUnitEnum_cd      SIUnitEnum = "cd"
	SIUnitEnum_deg     SIUnitEnum = "deg"
	SIUnitEnum_rad     SIUnitEnum = "rad"
	SIUnitEnum_sr      SIUnitEnum = "sr"
	SIUnitEnum_Gy      SIUnitEnum = "Gy"
	SIUnitEnum_q       SIUnitEnum = "q"
	SIUnitEnum_C       SIUnitEnum = "°C"
	SIUnitEnum_Sv      SIUnitEnum = "Sv"
	SIUnitEnum_F       SIUnitEnum = "F"
	SIUnitEnum_C_2     SIUnitEnum = "C"
	SIUnitEnum_S       SIUnitEnum = "S"
	SIUnitEnum_H       SIUnitEnum = "H"
	SIUnitEnum_V       SIUnitEnum = "V"
	SIUnitEnum_ohm     SIUnitEnum = "ohm"
	SIUnitEnum_J       SIUnitEnum = "J"
	SIUnitEnum_N       SIUnitEnum = "N"
	SIUnitEnum_Hz      SIUnitEnum = "Hz"
	SIUnitEnum_lx      SIUnitEnum = "lx"
	SIUnitEnum_Lm      SIUnitEnum = "Lm"
	SIUnitEnum_Wb      SIUnitEnum = "Wb"
	SIUnitEnum_T       SIUnitEnum = "T"
	SIUnitEnum_W       SIUnitEnum = "W"
	SIUnitEnum_Pa      SIUnitEnum = "Pa"
	SIUnitEnum_m_2     SIUnitEnum = "m^2"
	SIUnitEnum_m_3     SIUnitEnum = "m^3"
	SIUnitEnum_m_s     SIUnitEnum = "m/s"
	SIUnitEnum_m_s_2   SIUnitEnum = "m/s^2"
	SIUnitEnum_m_3_s   SIUnitEnum = "m^3/s"
	SIUnitEnum_m_m_3   SIUnitEnum = "m/m^3"
	SIUnitEnum_M       SIUnitEnum = "M"
	SIUnitEnum_kg_m_3  SIUnitEnum = "kg/m^3"
	SIUnitEnum_m_2_s   SIUnitEnum = "m^2/s"
	SIUnitEnum_W_m_K   SIUnitEnum = "W/m K"
	SIUnitEnum_J_K     SIUnitEnum = "J/K"
	SIUnitEnum_ppm     SIUnitEnum = "ppm"
	SIUnitEnum_s_1     SIUnitEnum = "s^-1"
	SIUnitEnum_rad_s   SIUnitEnum = "rad/s"
	SIUnitEnum_VA      SIUnitEnum = "VA"
	SIUnitEnum_Watts   SIUnitEnum = "Watts"
	SIUnitEnum_VAr     SIUnitEnum = "VAr"
	SIUnitEnum_phi     SIUnitEnum = "phi"
	SIUnitEnum_cos_phi SIUnitEnum = "cos_phi"
	SIUnitEnum_Vs      SIUnitEnum = "Vs"
	SIUnitEnum_V_2     SIUnitEnum = "V^2"
	SIUnitEnum_As      SIUnitEnum = "As"
	SIUnitEnum_A_2     SIUnitEnum = "A^2"
	SIUnitEnum_A_2_s   SIUnitEnum = "A^2 s"
	SIUnitEnum_VAh     SIUnitEnum = "VAh"
	SIUnitEnum_Wh      SIUnitEnum = "Wh"
	SIUnitEnum_VArh    SIUnitEnum = "VArh"
	SIUnitEnum_V_Hz    SIUnitEnum = "V/Hz"
	SIUnitEnum_b_s     SIUnitEnum = "b/s"
)

// ServiceSettingsEnum is generated from xs:simpleType "tServiceSettingsEnum".
type ServiceSettingsEnum string

const (
	ServiceSettingsEnum_Dyn  ServiceSettingsEnum = "Dyn"
	ServiceSettingsEnum_Conf ServiceSettingsEnum = "Conf"
	ServiceSettingsEnum_Fix  ServiceSettingsEnum = "Fix"
)

// TransformerWindingEnum is generated from xs:simpleType "tTransformerWindingEnum".
type TransformerWindingEnum string

const (
	TransformerWindingEnum_PTW TransformerWindingEnum = "PTW"
)

// TrgOptControlEnum is generated from xs:simpleType "tTrgOptControlEnum".
type TrgOptControlEnum string

const (
	TrgOptControlEnum_dchg   TrgOptControlEnum = "dchg"
	TrgOptControlEnum_qchg   TrgOptControlEnum = "qchg"
	TrgOptControlEnum_dupd   TrgOptControlEnum = "dupd"
	TrgOptControlEnum_period TrgOptControlEnum = "period"
	TrgOptControlEnum_none   TrgOptControlEnum = "none"
)

// TrgOptEnum is generated from xs:simpleType "tTrgOptEnum".
type TrgOptEnum string

const (
	TrgOptEnum_dchg TrgOptEnum = "dchg"
	TrgOptEnum_qchg TrgOptEnum = "qchg"
	TrgOptEnum_dupd TrgOptEnum = "dupd"
	TrgOptEnum_none TrgOptEnum = "none"
)

// UnitMultiplierEnum is generated from xs:simpleType "tUnitMultiplierEnum".
type UnitMultiplierEnum string

const (
	UnitMultiplierEnum_Unknown UnitMultiplierEnum = ""
	UnitMultiplierEnum_m       UnitMultiplierEnum = "m"
	UnitMultiplierEnum_k       UnitMultiplierEnum = "k"
	UnitMultiplierEnum_M       UnitMultiplierEnum = "M"
	UnitMultiplierEnum_mu      UnitMultiplierEnum = "mu"
	UnitMultiplierEnum_y       UnitMultiplierEnum = "y"
	UnitMultiplierEnum_z       UnitMultiplierEnum = "z"
	UnitMultiplierEnum_a       UnitMultiplierEnum = "a"
	UnitMultiplierEnum_f       UnitMultiplierEnum = "f"
	UnitMultiplierEnum_p       UnitMultiplierEnum = "p"
	UnitMultiplierEnum_n       UnitMultiplierEnum = "n"
	UnitMultiplierEnum_c       UnitMultiplierEnum = "c"
	UnitMultiplierEnum_d       UnitMultiplierEnum = "d"
	UnitMultiplierEnum_da      UnitMultiplierEnum = "da"
	UnitMultiplierEnum_h       UnitMultiplierEnum = "h"
	UnitMultiplierEnum_G       UnitMultiplierEnum = "G"
	UnitMultiplierEnum_T       UnitMultiplierEnum = "T"
	UnitMultiplierEnum_P       UnitMultiplierEnum = "P"
	UnitMultiplierEnum_E       UnitMultiplierEnum = "E"
	UnitMultiplierEnum_Z       UnitMultiplierEnum = "Z"
	UnitMultiplierEnum_Y       UnitMultiplierEnum = "Y"
)

// ValKindEnum is generated from xs:simpleType "tValKindEnum".
type ValKindEnum string

const (
	ValKindEnum_Spec ValKindEnum = "Spec"
	ValKindEnum_Conf ValKindEnum = "Conf"
	ValKindEnum_RO   ValKindEnum = "RO"
	ValKindEnum_Set  ValKindEnum = "Set"
)
