// Code generated by sclgen; DO NOT EDIT.
// Source bundle: IEC_61850-6.2003.SCL.1.7.full
// Entry schema: SCL.xsd
package v17

import "encoding/xml"

type AccessControl struct {
	ExtraElements []xml.Token `xml:",any"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type AccessPoint struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Server        *Server     `xml:"Server,omitempty"`
	LN            []LN        `xml:"LN,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Router        bool        `xml:"router,attr,omitempty"`
	Clock         bool        `xml:"clock,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Address struct {
	P []P `xml:"P"`
}

type Association struct {
	Kind          AssociationKindEnum `xml:"kind,attr"`
	AssociationID string              `xml:"associationID,attr,omitempty"`
	Prefix        string              `xml:"prefix,attr,omitempty"`
	LnClass       string              `xml:"lnClass,attr"`
	LnInst        string              `xml:"lnInst,attr"`
}

type BDA struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	BType         string      `xml:"bType,attr"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Type          string      `xml:"type,attr,omitempty"`
	Count         uint32      `xml:"count,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Bay struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	LNode               []LNode               `xml:"LNode,omitempty"`
	PowerTransformer    []PowerTransformer    `xml:"PowerTransformer,omitempty"`
	GeneralEquipment    []GeneralEquipment    `xml:"GeneralEquipment,omitempty"`
	ConductingEquipment []ConductingEquipment `xml:"ConductingEquipment,omitempty"`
	ConnectivityNode    []ConnectivityNode    `xml:"ConnectivityNode,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	Name                string                `xml:"name,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type BitRateInMbPerSec struct {
	Value      string             `xml:",chardata"`
	Unit       SIUnitEnum         `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type ClientLN struct {
	Prefix  string `xml:"prefix,attr,omitempty"`
	LnClass string `xml:"lnClass,attr"`
	LnInst  string `xml:"lnInst,attr"`
}

type Communication struct {
	Text          *Text        `xml:"Text,omitempty"`
	Private       []Private    `xml:"Private,omitempty"`
	SubNetwork    []SubNetwork `xml:"SubNetwork"`
	ExtraElements []xml.Token  `xml:",any"`
	Desc          string       `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr   `xml:",any,attr"`
}

type ConductingEquipment struct {
	Text          *Text          `xml:"Text,omitempty"`
	Private       []Private      `xml:"Private,omitempty"`
	LNode         []LNode        `xml:"LNode,omitempty"`
	Terminal      []Terminal     `xml:"Terminal,omitempty"`
	SubEquipment  []SubEquipment `xml:"SubEquipment,omitempty"`
	ExtraElements []xml.Token    `xml:",any"`
	Type          string         `xml:"type,attr"`
	Virtual       bool           `xml:"virtual,attr,omitempty"`
	Name          string         `xml:"name,attr"`
	Desc          string         `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr     `xml:",any,attr"`
}

type ConfLNs struct {
	FixPrefix bool `xml:"fixPrefix,attr,omitempty"`
	FixLnInst bool `xml:"fixLnInst,attr,omitempty"`
}

type ConnectedAP struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Address       *Address    `xml:"Address,omitempty"`
	GSE           []GSE       `xml:"GSE,omitempty"`
	SMV           []SMV       `xml:"SMV,omitempty"`
	PhysConn      []PhysConn  `xml:"PhysConn,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedName       string      `xml:"iedName,attr"`
	ApName        string      `xml:"apName,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ConnectivityNode struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	LNode         []LNode     `xml:"LNode,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	PathName      string      `xml:"pathName,attr"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ControlWithIEDName struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	IEDName       []string    `xml:"IEDName,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	ConfRev       uint32      `xml:"confRev,attr,omitempty"`
	DatSet        string      `xml:"datSet,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DA struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Fc            FCEnum      `xml:"fc,attr"`
	Dchg          bool        `xml:"dchg,attr,omitempty"`
	Qchg          bool        `xml:"qchg,attr,omitempty"`
	Dupd          bool        `xml:"dupd,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	BType         string      `xml:"bType,attr"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Type          string      `xml:"type,attr,omitempty"`
	Count         uint32      `xml:"count,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DAI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Val           []Val       `xml:"Val,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	SAddr         string      `xml:"sAddr,attr,omitempty"`
	ValKind       ValKindEnum `xml:"valKind,attr,omitempty"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DAType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	BDA           []BDA       `xml:"BDA"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DO struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Type          string      `xml:"type,attr"`
	AccessControl string      `xml:"accessControl,attr,omitempty"`
	Transient     bool        `xml:"transient,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DOI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDI           []SDI       `xml:"SDI,omitempty"`
	DAI           []DAI       `xml:"DAI,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	AccessControl string      `xml:"accessControl,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DOType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDO           []SDO       `xml:"SDO,omitempty"`
	DA            []DA        `xml:"DA,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	Cdc           string      `xml:"cdc,attr"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DataSet struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	FCDA          []FCDA      `xml:"FCDA"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type DataTypeTemplates struct {
	LNodeType []LNodeType `xml:"LNodeType"`
	DOType    []DOType    `xml:"DOType"`
	DAType    []DAType    `xml:"DAType,omitempty"`
	EnumType  []EnumType  `xml:"EnumType,omitempty"`
}

type DurationInMilliSec struct {
	Value      string             `xml:",chardata"`
	Unit       SIUnitEnum         `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type DurationInSec struct {
	Value      string             `xml:",chardata"`
	Unit       SIUnitEnum         `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type EnumType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	EnumVal       []EnumVal   `xml:"EnumVal"`
	ExtraElements []xml.Token `xml:",any"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type EnumVal struct {
	Value string `xml:",chardata"`
	Ord   int    `xml:"ord,attr"`
}

type ExtRef struct {
	DaName  string `xml:"daName,attr,omitempty"`
	IntAddr string `xml:"intAddr,attr,omitempty"`
	DoName  string `xml:"doName,attr"`
}

type FCDA struct {
	LdInst  string `xml:"ldInst,attr,omitempty"`
	Prefix  string `xml:"prefix,attr,omitempty"`
	LnClass string `xml:"lnClass,attr,omitempty"`
	LnInst  string `xml:"lnInst,attr,omitempty"`
	DoName  string `xml:"doName,attr,omitempty"`
	DaName  string `xml:"daName,attr,omitempty"`
	Fc      FCEnum `xml:"fc,attr"`
}

type Function struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	SubFunction      []SubFunction      `xml:"SubFunction,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type GSE struct {
	Text          *Text               `xml:"Text,omitempty"`
	Private       []Private           `xml:"Private,omitempty"`
	Address       *Address            `xml:"Address,omitempty"`
	MinTime       *DurationInMilliSec `xml:"MinTime,omitempty"`
	MaxTime       *DurationInMilliSec `xml:"MaxTime,omitempty"`
	ExtraElements []xml.Token         `xml:",any"`
	LdInst        string              `xml:"ldInst,attr"`
	CbName        string              `xml:"cbName,attr"`
	Desc          string              `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr          `xml:",any,attr"`
}

type GSEControl struct {
	Text          *Text              `xml:"Text,omitempty"`
	Private       []Private          `xml:"Private,omitempty"`
	IEDName       []string           `xml:"IEDName,omitempty"`
	ExtraElements []xml.Token        `xml:",any"`
	Type          GSEControlTypeEnum `xml:"type,attr,omitempty"`
	AppID         string             `xml:"appID,attr"`
	ConfRev       uint32             `xml:"confRev,attr,omitempty"`
	DatSet        string             `xml:"datSet,attr,omitempty"`
	Name          string             `xml:"name,attr"`
	Desc          string             `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr         `xml:",any,attr"`
}

type GSESettings struct {
	AppID     ServiceSettingsEnum `xml:"appID,attr,omitempty"`
	DataLabel ServiceSettingsEnum `xml:"dataLabel,attr,omitempty"`
	CbName    ServiceSettingsEnum `xml:"cbName,attr,omitempty"`
	DatSet    ServiceSettingsEnum `xml:"datSet,attr,omitempty"`
}

type GeneralEquipment struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	LNode         []LNode     `xml:"LNode,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Type          string      `xml:"type,attr"`
	Virtual       bool        `xml:"virtual,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Header struct {
	Text          *Text          `xml:"Text,omitempty"`
	History       *HistoryInline `xml:"History,omitempty"`
	Id            string         `xml:"id,attr"`
	Version       string         `xml:"version,attr,omitempty"`
	Revision      string         `xml:"revision,attr,omitempty"`
	ToolID        string         `xml:"toolID,attr,omitempty"`
	NameStructure string         `xml:"nameStructure,attr,omitempty"`
}

type Hitem struct {
	ExtraElements []xml.Token `xml:",any"`
	Version       string      `xml:"version,attr"`
	Revision      string      `xml:"revision,attr"`
	When          string      `xml:"when,attr"`
	Who           string      `xml:"who,attr,omitempty"`
	What          string      `xml:"what,attr,omitempty"`
	Why           string      `xml:"why,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type IED struct {
	Text          *Text         `xml:"Text,omitempty"`
	Private       []Private     `xml:"Private,omitempty"`
	Services      *Services     `xml:"Services,omitempty"`
	AccessPoint   []AccessPoint `xml:"AccessPoint"`
	ExtraElements []xml.Token   `xml:",any"`
	Type          string        `xml:"type,attr,omitempty"`
	Manufacturer  string        `xml:"manufacturer,attr,omitempty"`
	ConfigVersion string        `xml:"configVersion,attr,omitempty"`
	Name          string        `xml:"name,attr"`
	Desc          string        `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr    `xml:",any,attr"`
}

type Inputs struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtRef        []ExtRef    `xml:"ExtRef"`
	ExtraElements []xml.Token `xml:",any"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LDevice struct {
	Text          *Text          `xml:"Text,omitempty"`
	Private       []Private      `xml:"Private,omitempty"`
	LN0           LN0            `xml:"LN0"`
	LN            []LN           `xml:"LN,omitempty"`
	AccessControl *AccessControl `xml:"AccessControl,omitempty"`
	ExtraElements []xml.Token    `xml:",any"`
	Inst          string         `xml:"inst,attr"`
	LdName        string         `xml:"ldName,attr,omitempty"`
	Desc          string         `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr     `xml:",any,attr"`
}

type LN struct {
	Text          *Text           `xml:"Text,omitempty"`
	Private       []Private       `xml:"Private,omitempty"`
	DataSet       []DataSet       `xml:"DataSet,omitempty"`
	ReportControl []ReportControl `xml:"ReportControl,omitempty"`
	LogControl    []LogControl    `xml:"LogControl,omitempty"`
	DOI           []DOI           `xml:"DOI,omitempty"`
	Inputs        *Inputs         `xml:"Inputs,omitempty"`
	ExtraElements []xml.Token     `xml:",any"`
	LnClass       string          `xml:"lnClass,attr"`
	Inst          uint32          `xml:"inst,attr"`
	Prefix        string          `xml:"prefix,attr,omitempty"`
	LnType        string          `xml:"lnType,attr"`
	Desc          string          `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr      `xml:",any,attr"`
}

type LN0 struct {
	Text                *Text                 `xml:"Text,omitempty"`
	Private             []Private             `xml:"Private,omitempty"`
	DataSet             []DataSet             `xml:"DataSet,omitempty"`
	ReportControl       []ReportControl       `xml:"ReportControl,omitempty"`
	LogControl          []LogControl          `xml:"LogControl,omitempty"`
	DOI                 []DOI                 `xml:"DOI,omitempty"`
	Inputs              *Inputs               `xml:"Inputs,omitempty"`
	GSEControl          []GSEControl          `xml:"GSEControl,omitempty"`
	SampledValueControl []SampledValueControl `xml:"SampledValueControl,omitempty"`
	SettingControl      *SettingControl       `xml:"SettingControl,omitempty"`
	SCLControl          *SCLControl           `xml:"SCLControl,omitempty"`
	Log                 *Log                  `xml:"Log,omitempty"`
	ExtraElements       []xml.Token           `xml:",any"`
	LnClass             string                `xml:"lnClass,attr"`
	Inst                string                `xml:"inst,attr"`
	LnType              string                `xml:"lnType,attr"`
	Desc                string                `xml:"desc,attr,omitempty"`
	ExtraAttrs          []xml.Attr            `xml:",any,attr"`
}

type LNode struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	LnInst        string      `xml:"lnInst,attr,omitempty"`
	LnClass       string      `xml:"lnClass,attr"`
	IedName       string      `xml:"iedName,attr,omitempty"`
	LdInst        string      `xml:"ldInst,attr,omitempty"`
	Prefix        string      `xml:"prefix,attr,omitempty"`
	LnType        string      `xml:"lnType,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LNodeType struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	DO            []DO        `xml:"DO"`
	ExtraElements []xml.Token `xml:",any"`
	IedType       string      `xml:"iedType,attr,omitempty"`
	LnClass       string      `xml:"lnClass,attr"`
	Id            string      `xml:"id,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Log struct {
	ExtraElements []xml.Token `xml:",any"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LogControl struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	TrgOps        *TrgOps     `xml:"TrgOps,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	LogName       string      `xml:"logName,attr"`
	LogEna        bool        `xml:"logEna,attr,omitempty"`
	ReasonCode    bool        `xml:"reasonCode,attr,omitempty"`
	IntgPd        uint32      `xml:"intgPd,attr,omitempty"`
	DatSet        string      `xml:"datSet,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type LogSettings struct {
	LogEna ServiceSettingsEnum `xml:"logEna,attr,omitempty"`
	TrgOps ServiceSettingsEnum `xml:"trgOps,attr,omitempty"`
	IntgPd ServiceSettingsEnum `xml:"intgPd,attr,omitempty"`
	CbName ServiceSettingsEnum `xml:"cbName,attr,omitempty"`
	DatSet ServiceSettingsEnum `xml:"datSet,attr,omitempty"`
}

type P struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_APPID is generated from xs:complexType "tP_APPID".
type P_APPID struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_IP is generated from xs:complexType "tP_IP".
type P_IP struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_IP_GATEWAY is generated from xs:complexType "tP_IP-GATEWAY".
type P_IP_GATEWAY struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_IP_SUBNET is generated from xs:complexType "tP_IP-SUBNET".
type P_IP_SUBNET struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_MAC_Address is generated from xs:complexType "tP_MAC-Address".
type P_MAC_Address struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_AE_Invoke is generated from xs:complexType "tP_OSI-AE-Invoke".
type P_OSI_AE_Invoke struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_AE_Qualifier is generated from xs:complexType "tP_OSI-AE-Qualifier".
type P_OSI_AE_Qualifier struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_AP_Invoke is generated from xs:complexType "tP_OSI-AP-Invoke".
type P_OSI_AP_Invoke struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_AP_Title is generated from xs:complexType "tP_OSI-AP-Title".
type P_OSI_AP_Title struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_NSAP is generated from xs:complexType "tP_OSI-NSAP".
type P_OSI_NSAP struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_PSEL is generated from xs:complexType "tP_OSI-PSEL".
type P_OSI_PSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_SSEL is generated from xs:complexType "tP_OSI-SSEL".
type P_OSI_SSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_OSI_TSEL is generated from xs:complexType "tP_OSI-TSEL".
type P_OSI_TSEL struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_VLAN_ID is generated from xs:complexType "tP_VLAN-ID".
type P_VLAN_ID struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

// P_VLAN_PRIORITY is generated from xs:complexType "tP_VLAN-PRIORITY".
type P_VLAN_PRIORITY struct {
	Value string `xml:",chardata"`
	Type  string `xml:"type,attr"`
}

type PhysConn struct {
	P    []P    `xml:"P,omitempty"`
	Type string `xml:"type,attr"`
}

type PowerTransformer struct {
	Text               *Text                `xml:"Text,omitempty"`
	Private            []Private            `xml:"Private,omitempty"`
	LNode              []LNode              `xml:"LNode,omitempty"`
	TransformerWinding []TransformerWinding `xml:"TransformerWinding"`
	ExtraElements      []xml.Token          `xml:",any"`
	Type               PowerTransformerEnum `xml:"type,attr"`
	Virtual            bool                 `xml:"virtual,attr,omitempty"`
	Name               string               `xml:"name,attr"`
	Desc               string               `xml:"desc,attr,omitempty"`
	ExtraAttrs         []xml.Attr           `xml:",any,attr"`
}

type Private struct {
	InnerXML      string      `xml:",innerxml"`
	ExtraElements []xml.Token `xml:",any"`
	Type          string      `xml:"type,attr,omitempty"`
	Source        string      `xml:"source,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type ReportControl struct {
	Text          *Text           `xml:"Text,omitempty"`
	Private       []Private       `xml:"Private,omitempty"`
	TrgOps        *TrgOps         `xml:"TrgOps,omitempty"`
	OptFields     OptFieldsInline `xml:"OptFields"`
	RptEnabled    *RptEnabled     `xml:"RptEnabled,omitempty"`
	ExtraElements []xml.Token     `xml:",any"`
	RptID         string          `xml:"rptID,attr,omitempty"`
	ConfRev       uint32          `xml:"confRev,attr"`
	Buffered      bool            `xml:"buffered,attr,omitempty"`
	BufTime       uint32          `xml:"bufTime,attr,omitempty"`
	IntgPd        uint32          `xml:"intgPd,attr,omitempty"`
	DatSet        string          `xml:"datSet,attr,omitempty"`
	Name          string          `xml:"name,attr"`
	Desc          string          `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr      `xml:",any,attr"`
}

type ReportSettings struct {
	RptID     ServiceSettingsEnum `xml:"rptID,attr,omitempty"`
	OptFields ServiceSettingsEnum `xml:"optFields,attr,omitempty"`
	BufTime   ServiceSettingsEnum `xml:"bufTime,attr,omitempty"`
	TrgOps    ServiceSettingsEnum `xml:"trgOps,attr,omitempty"`
	IntgPd    ServiceSettingsEnum `xml:"intgPd,attr,omitempty"`
	CbName    ServiceSettingsEnum `xml:"cbName,attr,omitempty"`
	DatSet    ServiceSettingsEnum `xml:"datSet,attr,omitempty"`
}

type RptEnabled struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ClientLN      []ClientLN  `xml:"ClientLN,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Max           uint32      `xml:"max,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SCLControl struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SDI struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	SDI           []*SDI      `xml:"SDI,omitempty"`
	DAI           []DAI       `xml:"DAI,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Name          string      `xml:"name,attr"`
	Ix            uint32      `xml:"ix,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SDO struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Type          string      `xml:"type,attr"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SMV struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	Address       *Address    `xml:"Address,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	LdInst        string      `xml:"ldInst,attr"`
	CbName        string      `xml:"cbName,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SMVSettings struct {
	SmpRate     []string            `xml:"SmpRate"`
	SvID        ServiceSettingsEnum `xml:"svID,attr,omitempty"`
	OptFields   ServiceSettingsEnum `xml:"optFields,attr,omitempty"`
	SmpRateAttr ServiceSettingsEnum `xml:"smpRate,attr,omitempty"`
	CbName      ServiceSettingsEnum `xml:"cbName,attr,omitempty"`
	DatSet      ServiceSettingsEnum `xml:"datSet,attr,omitempty"`
}

type SampledValueControl struct {
	Text          *Text         `xml:"Text,omitempty"`
	Private       []Private     `xml:"Private,omitempty"`
	IEDName       []string      `xml:"IEDName,omitempty"`
	SmvOpts       SmvOptsInline `xml:"SmvOpts"`
	ExtraElements []xml.Token   `xml:",any"`
	SmvID         string        `xml:"smvID,attr"`
	Multicast     bool          `xml:"multicast,attr,omitempty"`
	SmpRate       uint32        `xml:"smpRate,attr"`
	NofASDU       uint32        `xml:"nofASDU,attr"`
	ConfRev       uint32        `xml:"confRev,attr,omitempty"`
	DatSet        string        `xml:"datSet,attr,omitempty"`
	Name          string        `xml:"name,attr"`
	Desc          string        `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr    `xml:",any,attr"`
}

type Server struct {
	Text           *Text                `xml:"Text,omitempty"`
	Private        []Private            `xml:"Private,omitempty"`
	Authentication AuthenticationInline `xml:"Authentication"`
	LDevice        []LDevice            `xml:"LDevice"`
	Association    []Association        `xml:"Association,omitempty"`
	ExtraElements  []xml.Token          `xml:",any"`
	Timeout        uint32               `xml:"timeout,attr,omitempty"`
	Desc           string               `xml:"desc,attr,omitempty"`
	ExtraAttrs     []xml.Attr           `xml:",any,attr"`
}

type ServiceWithMax struct {
	Max uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndClient struct {
	Client bool   `xml:"client,attr,omitempty"`
	Max    uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndMaxAttributes struct {
	MaxAttributes uint32 `xml:"maxAttributes,attr,omitempty"`
	Max           uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndMaxAttributesAndModify struct {
	Modify        bool   `xml:"modify,attr,omitempty"`
	MaxAttributes uint32 `xml:"maxAttributes,attr,omitempty"`
	Max           uint32 `xml:"max,attr"`
}

type ServiceWithMaxAndModify struct {
	Modify bool   `xml:"modify,attr,omitempty"`
	Max    uint32 `xml:"max,attr"`
}

type ServiceYesNo struct {
}

type Services struct {
	DynAssociation          *ServiceYesNo                            `xml:"DynAssociation,omitempty"`
	SettingGroups           *SettingGroupsInline                     `xml:"SettingGroups,omitempty"`
	GetDirectory            *ServiceYesNo                            `xml:"GetDirectory,omitempty"`
	GetDataObjectDefinition *ServiceYesNo                            `xml:"GetDataObjectDefinition,omitempty"`
	DataObjectDirectory     *ServiceYesNo                            `xml:"DataObjectDirectory,omitempty"`
	GetDataSetValue         *ServiceYesNo                            `xml:"GetDataSetValue,omitempty"`
	SetDataSetValue         *ServiceYesNo                            `xml:"SetDataSetValue,omitempty"`
	DataSetDirectory        *ServiceYesNo                            `xml:"DataSetDirectory,omitempty"`
	ConfDataSet             *ServiceWithMaxAndMaxAttributesAndModify `xml:"ConfDataSet,omitempty"`
	DynDataSet              *ServiceWithMaxAndMaxAttributes          `xml:"DynDataSet,omitempty"`
	ReadWrite               *ServiceYesNo                            `xml:"ReadWrite,omitempty"`
	TimerActivatedControl   *ServiceYesNo                            `xml:"TimerActivatedControl,omitempty"`
	ConfReportControl       *ServiceWithMax                          `xml:"ConfReportControl,omitempty"`
	GetCBValues             *ServiceYesNo                            `xml:"GetCBValues,omitempty"`
	ConfLogControl          *ServiceWithMax                          `xml:"ConfLogControl,omitempty"`
	ReportSettings          *ReportSettings                          `xml:"ReportSettings,omitempty"`
	LogSettings             *LogSettings                             `xml:"LogSettings,omitempty"`
	GSESettings             *GSESettings                             `xml:"GSESettings,omitempty"`
	SMVSettings             *SMVSettings                             `xml:"SMVSettings,omitempty"`
	GSEDir                  *ServiceYesNo                            `xml:"GSEDir,omitempty"`
	GOOSE                   *ServiceWithMaxAndClient                 `xml:"GOOSE,omitempty"`
	GSSE                    *ServiceWithMaxAndClient                 `xml:"GSSE,omitempty"`
	FileHandling            *ServiceYesNo                            `xml:"FileHandling,omitempty"`
	ConfLNs                 *ConfLNs                                 `xml:"ConfLNs,omitempty"`
}

type SettingControl struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	NumOfSGs      uint32      `xml:"numOfSGs,attr"`
	ActSG         uint32      `xml:"actSG,attr,omitempty"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SubEquipment struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	LNode         []LNode     `xml:"LNode,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Phase         PhaseEnum   `xml:"phase,attr,omitempty"`
	Virtual       bool        `xml:"virtual,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type SubFunction struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type SubNetwork struct {
	Text          *Text              `xml:"Text,omitempty"`
	Private       []Private          `xml:"Private,omitempty"`
	BitRate       *BitRateInMbPerSec `xml:"BitRate,omitempty"`
	ConnectedAP   []ConnectedAP      `xml:"ConnectedAP"`
	ExtraElements []xml.Token        `xml:",any"`
	Type          string             `xml:"type,attr,omitempty"`
	Name          string             `xml:"name,attr"`
	Desc          string             `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr         `xml:",any,attr"`
}

type Substation struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	PowerTransformer []PowerTransformer `xml:"PowerTransformer,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	VoltageLevel     []VoltageLevel     `xml:"VoltageLevel"`
	Function         []Function         `xml:"Function,omitempty"`
	ExtraElements    []xml.Token        `xml:",any"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type TapChanger struct {
	Text          *Text       `xml:"Text,omitempty"`
	Private       []Private   `xml:"Private,omitempty"`
	LNode         []LNode     `xml:"LNode,omitempty"`
	ExtraElements []xml.Token `xml:",any"`
	Type          string      `xml:"type,attr"`
	Virtual       bool        `xml:"virtual,attr,omitempty"`
	Name          string      `xml:"name,attr"`
	Desc          string      `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type Terminal struct {
	Text             *Text       `xml:"Text,omitempty"`
	Private          []Private   `xml:"Private,omitempty"`
	ExtraElements    []xml.Token `xml:",any"`
	Name             string      `xml:"name,attr,omitempty"`
	ConnectivityNode string      `xml:"connectivityNode,attr"`
	SubstationName   string      `xml:"substationName,attr"`
	VoltageLevelName string      `xml:"voltageLevelName,attr"`
	BayName          string      `xml:"bayName,attr"`
	CNodeName        string      `xml:"cNodeName,attr"`
	Desc             string      `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr  `xml:",any,attr"`
}

type Text struct {
	ExtraElements []xml.Token `xml:",any"`
	Source        string      `xml:"source,attr,omitempty"`
	ExtraAttrs    []xml.Attr  `xml:",any,attr"`
}

type TransformerWinding struct {
	Text          *Text                  `xml:"Text,omitempty"`
	Private       []Private              `xml:"Private,omitempty"`
	LNode         []LNode                `xml:"LNode,omitempty"`
	Terminal      []Terminal             `xml:"Terminal,omitempty"`
	SubEquipment  []SubEquipment         `xml:"SubEquipment,omitempty"`
	TapChanger    *TapChanger            `xml:"TapChanger,omitempty"`
	ExtraElements []xml.Token            `xml:",any"`
	Type          TransformerWindingEnum `xml:"type,attr"`
	Virtual       bool                   `xml:"virtual,attr,omitempty"`
	Name          string                 `xml:"name,attr"`
	Desc          string                 `xml:"desc,attr,omitempty"`
	ExtraAttrs    []xml.Attr             `xml:",any,attr"`
}

type TrgOps struct {
	Dchg   bool `xml:"dchg,attr,omitempty"`
	Qchg   bool `xml:"qchg,attr,omitempty"`
	Dupd   bool `xml:"dupd,attr,omitempty"`
	Period bool `xml:"period,attr,omitempty"`
}

type Val struct {
	Value  string `xml:",chardata"`
	SGroup uint32 `xml:"sGroup,attr,omitempty"`
}

type ValueWithUnit struct {
	Value      float64            `xml:",chardata"`
	Unit       SIUnitEnum         `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type Voltage struct {
	Value      string             `xml:",chardata"`
	Unit       SIUnitEnum         `xml:"unit,attr"`
	Multiplier UnitMultiplierEnum `xml:"multiplier,attr,omitempty"`
}

type VoltageLevel struct {
	Text             *Text              `xml:"Text,omitempty"`
	Private          []Private          `xml:"Private,omitempty"`
	LNode            []LNode            `xml:"LNode,omitempty"`
	PowerTransformer []PowerTransformer `xml:"PowerTransformer,omitempty"`
	GeneralEquipment []GeneralEquipment `xml:"GeneralEquipment,omitempty"`
	Voltage          *Voltage           `xml:"Voltage,omitempty"`
	Bay              []Bay              `xml:"Bay"`
	ExtraElements    []xml.Token        `xml:",any"`
	Name             string             `xml:"name,attr"`
	Desc             string             `xml:"desc,attr,omitempty"`
	ExtraAttrs       []xml.Attr         `xml:",any,attr"`
}

type AuthenticationInline struct {
	None        bool `xml:"none,attr,omitempty"`
	Password    bool `xml:"password,attr,omitempty"`
	Weak        bool `xml:"weak,attr,omitempty"`
	Strong      bool `xml:"strong,attr,omitempty"`
	Certificate bool `xml:"certificate,attr,omitempty"`
}

type HistoryInline struct {
	Hitem []Hitem `xml:"Hitem"`
}

type OptFieldsInline struct {
	SeqNum     bool `xml:"seqNum,attr,omitempty"`
	TimeStamp  bool `xml:"timeStamp,attr,omitempty"`
	DataSet    bool `xml:"dataSet,attr,omitempty"`
	ReasonCode bool `xml:"reasonCode,attr,omitempty"`
	DataRef    bool `xml:"dataRef,attr,omitempty"`
	EntryID    bool `xml:"entryID,attr,omitempty"`
	ConfigRef  bool `xml:"configRef,attr,omitempty"`
}

type SettingGroupsInline struct {
	SGEdit *ServiceYesNo `xml:"SGEdit,omitempty"`
	ConfSG *ServiceYesNo `xml:"ConfSG,omitempty"`
}

type SmvOptsInline struct {
	RefreshTime        bool `xml:"refreshTime,attr,omitempty"`
	SampleSynchronized bool `xml:"sampleSynchronized,attr,omitempty"`
	SampleRate         bool `xml:"sampleRate,attr,omitempty"`
	Security           bool `xml:"security,attr,omitempty"`
	DataRef            bool `xml:"dataRef,attr,omitempty"`
}

// SCL is the root element of an IEC 61850 SCL document.
type SCL struct {
	XMLName           xml.Name           `xml:"http://www.iec.ch/61850/2003/SCL SCL"`
	Text              *Text              `xml:"Text,omitempty"`
	Private           []Private          `xml:"Private,omitempty"`
	Header            Header             `xml:"Header"`
	Substation        []Substation       `xml:"Substation,omitempty"`
	Communication     *Communication     `xml:"Communication,omitempty"`
	IED               []IED              `xml:"IED,omitempty"`
	DataTypeTemplates *DataTypeTemplates `xml:"DataTypeTemplates,omitempty"`
	ExtraElements     []xml.Token        `xml:",any"`
	ExtraAttrs        []xml.Attr         `xml:",any,attr"`
}
